/*
 * Copyright (c) 2022 Andreas Signer <asigner@gmail.com>
 *
 * This file is part of vicedebug.
 *
 * vicedebug is free software: you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * vicedebug is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with vicedebug.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "disassembler_z80.h"

#include <string>
#include <QString>
#include <QDebug>

namespace vicedebug {

namespace {

enum ParamType {
    NONE, // No param
    ABS8,  // 8bit value
    ABS16, // 16bit value
    REL,  // 8bit relative
    DISP, // 8bit displacement
    DISP_ABS8,  // 8bit displacement, 8bit immediate value
};

struct InstrDesc {
    std::string instr;
    ParamType param;
    bool illegal;
};

InstrDesc opcodes[256] = {
    /* 0x00 */  {"NOP", NONE, false},
    /* 0x01 */  {"LD BC, #%s", ABS16, false},
    /* 0x02 */  {"LD (BC),A", NONE, false},
    /* 0x03 */  {"INC BC", NONE, false},
    /* 0x04 */  {"INC B", NONE, false},
    /* 0x05 */  {"DEC B", NONE, false},
    /* 0x06 */  {"LD B, #%s", ABS8, false},
    /* 0x07 */  {"RLCA", NONE, false},
    /* 0x08 */  {"EX AF,AF'", NONE, false},
    /* 0x09 */  {"ADD HL,BC", NONE, false},
    /* 0x0a */  {"LD A,(BC)", NONE, false},
    /* 0x0b */  {"DEC BC", NONE, false},
    /* 0x0c */  {"INC C", NONE, false},
    /* 0x0d */  {"DEC C", NONE, false},
    /* 0x0e */  {"LD C, #%s", ABS8, false},
    /* 0x0f */  {"RRCA", NONE, false},
    /* 0x10 */  {"DJNZ %s", REL, false},
    /* 0x11 */  {"LD DE, #%s", ABS16, false},
    /* 0x12 */  {"LD (DE),A", NONE, false},
    /* 0x13 */  {"INC DE", NONE, false},
    /* 0x14 */  {"INC D", NONE, false},
    /* 0x15 */  {"DEC D", NONE, false},
    /* 0x16 */  {"LD D, #%s", ABS8, false},
    /* 0x17 */  {"RLA", NONE, false},
    /* 0x18 */  {"JR %s", REL, false},
    /* 0x19 */  {"ADD HL,DE", NONE, false},
    /* 0x1a */  {"LD A,(DE)", NONE, false},
    /* 0x1b */  {"DEC DE", NONE, false},
    /* 0x1c */  {"INC E", NONE, false},
    /* 0x1d */  {"DEC E", NONE, false},
    /* 0x1e */  {"LD E, #%s", ABS8, false},
    /* 0x1f */  {"RRA", NONE, false},
    /* 0x20 */  {"JR NZ, %s", REL, false},
    /* 0x21 */  {"LD HL, #%s", ABS16, false},
    /* 0x22 */  {"LD (%s),HL", ABS16, false},
    /* 0x23 */  {"INC HL", NONE, false},
    /* 0x24 */  {"INC H", NONE, false},
    /* 0x25 */  {"DEC H", NONE, false},
    /* 0x26 */  {"LD H, #%s", ABS8, false},
    /* 0x27 */  {"DAA", NONE, false},
    /* 0x28 */  {"JR Z, %s", REL, false},
    /* 0x29 */  {"ADD HL,HL", NONE, false},
    /* 0x2a */  {"LD HL, (%s)", ABS16, false},
    /* 0x2b */  {"DEC HL", NONE, false},
    /* 0x2c */  {"INC L", NONE, false},
    /* 0x2d */  {"DEC L", NONE, false},
    /* 0x2e */  {"LD L, #%s", ABS8, false},
    /* 0x2f */  {"CPL", NONE, false},
    /* 0x30 */  {"JR NC, %s", REL, false},
    /* 0x31 */  {"LD SP, #%s", ABS16, false},
    /* 0x32 */  {"LD (%s),A", ABS16, false},
    /* 0x33 */  {"INC SP", NONE, false},
    /* 0x34 */  {"INC (HL)", NONE, false},
    /* 0x35 */  {"DEC (HL)", NONE, false},
    /* 0x36 */  {"LD (HL), #%s", ABS8, false},
    /* 0x37 */  {"SCF", NONE, false},
    /* 0x38 */  {"JR C, %s", REL, false},
    /* 0x39 */  {"ADD HL,SP", NONE, false},
    /* 0x3a */  {"LD A, (%s)", ABS16, false},
    /* 0x3b */  {"DEC SP", NONE, false},
    /* 0x3c */  {"INC A", NONE, false},
    /* 0x3d */  {"DEC A", NONE, false},
    /* 0x3e */  {"LD A, #%s", ABS8, false},
    /* 0x3f */  {"CCF", NONE, false},
    /* 0x40 */  {"LD B,B", NONE, false},
    /* 0x41 */  {"LD B,C", NONE, false},
    /* 0x42 */  {"LD B,D", NONE, false},
    /* 0x43 */  {"LD B,E", NONE, false},
    /* 0x44 */  {"LD B,H", NONE, false},
    /* 0x45 */  {"LD B,L", NONE, false},
    /* 0x46 */  {"LD B,(HL)", NONE, false},
    /* 0x47 */  {"LD B,A", NONE, false},
    /* 0x48 */  {"LD C,B", NONE, false},
    /* 0x49 */  {"LD C,C", NONE, false},
    /* 0x4a */  {"LD C,D", NONE, false},
    /* 0x4b */  {"LD C,E", NONE, false},
    /* 0x4c */  {"LD C,H", NONE, false},
    /* 0x4d */  {"LD C,L", NONE, false},
    /* 0x4e */  {"LD C,(HL)", NONE, false},
    /* 0x4f */  {"LD C,A", NONE, false},
    /* 0x50 */  {"LD D,B", NONE, false},
    /* 0x51 */  {"LD D,C", NONE, false},
    /* 0x52 */  {"LD D,D", NONE, false},
    /* 0x53 */  {"LD D,E", NONE, false},
    /* 0x54 */  {"LD D,H", NONE, false},
    /* 0x55 */  {"LD D,L", NONE, false},
    /* 0x56 */  {"LD D,(HL)", NONE, false},
    /* 0x57 */  {"LD D,A", NONE, false},
    /* 0x58 */  {"LD E,B", NONE, false},
    /* 0x59 */  {"LD E,C", NONE, false},
    /* 0x5a */  {"LD E,D", NONE, false},
    /* 0x5b */  {"LD E,E", NONE, false},
    /* 0x5c */  {"LD E,H", NONE, false},
    /* 0x5d */  {"LD E,L", NONE, false},
    /* 0x5e */  {"LD E,(HL)", NONE, false},
    /* 0x5f */  {"LD E,A", NONE, false},
    /* 0x60 */  {"LD H,B", NONE, false},
    /* 0x61 */  {"LD H,C", NONE, false},
    /* 0x62 */  {"LD H,D", NONE, false},
    /* 0x63 */  {"LD H,E", NONE, false},
    /* 0x64 */  {"LD H,H", NONE, false},
    /* 0x65 */  {"LD H,L", NONE, false},
    /* 0x66 */  {"LD H,(HL)", NONE, false},
    /* 0x67 */  {"LD H,A", NONE, false},
    /* 0x68 */  {"LD L,B", NONE, false},
    /* 0x69 */  {"LD L,C", NONE, false},
    /* 0x6a */  {"LD L,D", NONE, false},
    /* 0x6b */  {"LD L,E", NONE, false},
    /* 0x6c */  {"LD L,H", NONE, false},
    /* 0x6d */  {"LD L,L", NONE, false},
    /* 0x6e */  {"LD L,(HL)", NONE, false},
    /* 0x6f */  {"LD L,A", NONE, false},
    /* 0x70 */  {"LD (HL),B", NONE, false},
    /* 0x71 */  {"LD (HL),C", NONE, false},
    /* 0x72 */  {"LD (HL),D", NONE, false},
    /* 0x73 */  {"LD (HL),E", NONE, false},
    /* 0x74 */  {"LD (HL),H", NONE, false},
    /* 0x75 */  {"LD (HL),L", NONE, false},
    /* 0x76 */  {"HALT", NONE, false},
    /* 0x77 */  {"LD (HL),A", NONE, false},
    /* 0x78 */  {"LD A,B", NONE, false},
    /* 0x79 */  {"LD A,C", NONE, false},
    /* 0x7a */  {"LD A,D", NONE, false},
    /* 0x7b */  {"LD A,E", NONE, false},
    /* 0x7c */  {"LD A,H", NONE, false},
    /* 0x7d */  {"LD A,L", NONE, false},
    /* 0x7e */  {"LD A,(HL)", NONE, false},
    /* 0x7f */  {"LD A,A", NONE, false},
    /* 0x80 */  {"ADD B", NONE, false},
    /* 0x81 */  {"ADD C", NONE, false},
    /* 0x82 */  {"ADD D", NONE, false},
    /* 0x83 */  {"ADD E", NONE, false},
    /* 0x84 */  {"ADD H", NONE, false},
    /* 0x85 */  {"ADD L", NONE, false},
    /* 0x86 */  {"ADD (HL)", NONE, false},
    /* 0x87 */  {"ADD A", NONE, false},
    /* 0x88 */  {"ADC B", NONE, false},
    /* 0x89 */  {"ADC C", NONE, false},
    /* 0x8a */  {"ADC D", NONE, false},
    /* 0x8b */  {"ADC E", NONE, false},
    /* 0x8c */  {"ADC H", NONE, false},
    /* 0x8d */  {"ADC L", NONE, false},
    /* 0x8e */  {"ADC (HL)", NONE, false},
    /* 0x8f */  {"ADC A", NONE, false},
    /* 0x90 */  {"SUB B", NONE, false},
    /* 0x91 */  {"SUB C", NONE, false},
    /* 0x92 */  {"SUB D", NONE, false},
    /* 0x93 */  {"SUB E", NONE, false},
    /* 0x94 */  {"SUB H", NONE, false},
    /* 0x95 */  {"SUB L", NONE, false},
    /* 0x96 */  {"SUB (HL)", NONE, false},
    /* 0x97 */  {"SUB A", NONE, false},
    /* 0x98 */  {"SBC B", NONE, false},
    /* 0x99 */  {"SBC C", NONE, false},
    /* 0x9a */  {"SBC D", NONE, false},
    /* 0x9b */  {"SBC E", NONE, false},
    /* 0x9c */  {"SBC H", NONE, false},
    /* 0x9d */  {"SBC L", NONE, false},
    /* 0x9e */  {"SBC (HL)", NONE, false},
    /* 0x9f */  {"SBC A", NONE, false},
    /* 0xa0 */  {"AND B", NONE, false},
    /* 0xa1 */  {"AND C", NONE, false},
    /* 0xa2 */  {"AND D", NONE, false},
    /* 0xa3 */  {"AND E", NONE, false},
    /* 0xa4 */  {"AND H", NONE, false},
    /* 0xa5 */  {"AND L", NONE, false},
    /* 0xa6 */  {"AND (HL)", NONE, false},
    /* 0xa7 */  {"AND A", NONE, false},
    /* 0xa8 */  {"XOR B", NONE, false},
    /* 0xa9 */  {"XOR C", NONE, false},
    /* 0xaa */  {"XOR D", NONE, false},
    /* 0xab */  {"XOR E", NONE, false},
    /* 0xac */  {"XOR H", NONE, false},
    /* 0xad */  {"XOR L", NONE, false},
    /* 0xae */  {"XOR (HL)", NONE, false},
    /* 0xaf */  {"XOR A", NONE, false},
    /* 0xb0 */  {"OR B", NONE, false},
    /* 0xb1 */  {"OR C", NONE, false},
    /* 0xb2 */  {"OR D", NONE, false},
    /* 0xb3 */  {"OR E", NONE, false},
    /* 0xb4 */  {"OR H", NONE, false},
    /* 0xb5 */  {"OR L", NONE, false},
    /* 0xb6 */  {"OR (HL)", NONE, false},
    /* 0xb7 */  {"OR A", NONE, false},
    /* 0xb8 */  {"CP B", NONE, false},
    /* 0xb9 */  {"CP C", NONE, false},
    /* 0xba */  {"CP D", NONE, false},
    /* 0xbb */  {"CP E", NONE, false},
    /* 0xbc */  {"CP H", NONE, false},
    /* 0xbd */  {"CP L", NONE, false},
    /* 0xbe */  {"CP (HL)", NONE, false},
    /* 0xbf */  {"CP A", NONE, false},
    /* 0xc0 */  {"RET NZ", NONE, false},
    /* 0xc1 */  {"POP BC", NONE, false},
    /* 0xc2 */  {"JP NZ, %s", ABS16, false},
    /* 0xc3 */  {"JP %s", ABS16, false},
    /* 0xc4 */  {"CALL NZ, %s", ABS16, false},
    /* 0xc5 */  {"PUSH BC", NONE, false},
    /* 0xc6 */  {"ADD #%s", ABS8, false},
    /* 0xc7 */  {"RST 00", NONE, false},
    /* 0xc8 */  {"RET Z", NONE, false},
    /* 0xc9 */  {"RET", NONE, false},
    /* 0xca */  {"JP Z, %s", ABS16, false},
    /* 0xcb */  {"???", NONE, true},
    /* 0xcc */  {"CALL Z, %s", ABS16, false},
    /* 0xcd */  {"CALL %s", ABS16, false},
    /* 0xce */  {"ADC #%s", ABS8, false},
    /* 0xcf */  {"RST 08", NONE, false},
    /* 0xd0 */  {"RET NC", NONE, false},
    /* 0xd1 */  {"POP DE", NONE, false},
    /* 0xd2 */  {"JP NC, %s", ABS16, false},
    /* 0xd3 */  {"OUTA %s", ABS8, false},
    /* 0xd4 */  {"CALL NC, %s", ABS16, false},
    /* 0xd5 */  {"PUSH DE", NONE, false},
    /* 0xd6 */  {"SUB #%s", ABS8, false},
    /* 0xd7 */  {"RST 10", NONE, false},
    /* 0xd8 */  {"RET C", NONE, false},
    /* 0xd9 */  {"EXX", NONE, false},
    /* 0xda */  {"JP C, %s", ABS16, false},
    /* 0xdb */  {"INA %s", ABS8, false},
    /* 0xdc */  {"CALL C, %s", ABS16, false},
    /* 0xdd */  {"???", NONE, true},
    /* 0xde */  {"SBC #%s", ABS8, false},
    /* 0xdf */  {"RST 18", NONE, false},
    /* 0xe0 */  {"RET PO", NONE, false},
    /* 0xe1 */  {"POP HL", NONE, false},
    /* 0xe2 */  {"JP PO, %s", ABS16, false},
    /* 0xe3 */  {"EX (SP),HL", NONE, false},
    /* 0xe4 */  {"CALL PO, %s", ABS16, false},
    /* 0xe5 */  {"PUSH HL", NONE, false},
    /* 0xe6 */  {"AND #%s", ABS8, false},
    /* 0xe7 */  {"RST 20", NONE, false},
    /* 0xe8 */  {"RET PE", NONE, false},
    /* 0xe9 */  {"JP (HL)", NONE, false},
    /* 0xea */  {"JP PE, %s", ABS16, false},
    /* 0xeb */  {"EX DE,HL", NONE, false},
    /* 0xec */  {"CALL PE, %s", ABS16, false},
    /* 0xed */  {"???", NONE, true},
    /* 0xee */  {"XOR #%s", ABS8, false},
    /* 0xef */  {"RST 28", NONE, false},
    /* 0xf0 */  {"RET P", NONE, false},
    /* 0xf1 */  {"POP AF", NONE, false},
    /* 0xf2 */  {"JP P, %s", ABS16, false},
    /* 0xf3 */  {"DI", NONE, false},
    /* 0xf4 */  {"CALL P, %s", ABS16, false},
    /* 0xf5 */  {"PUSH AF", NONE, false},
    /* 0xf6 */  {"OR #%s", ABS8, false},
    /* 0xf7 */  {"RST 30", NONE, false},
    /* 0xf8 */  {"RET M", NONE, false},
    /* 0xf9 */  {"LD SP,HL", NONE, false},
    /* 0xfa */  {"JP M, %s", ABS16, false},
    /* 0xfb */  {"EI", NONE, false},
    /* 0xfc */  {"CALL M, %s", ABS16, false},
    /* 0xfd */  {"???", NONE, true},
    /* 0xfe */  {"CP #%s", ABS8, false},
    /* 0xff */  {"RST 38", NONE, false},
};

InstrDesc opcodes_cb[256] = {
    /* 0x00 */  {"RLC B", NONE, false},
    /* 0x01 */  {"RLC C", NONE, false},
    /* 0x02 */  {"RLC D", NONE, false},
    /* 0x03 */  {"RLC E", NONE, false},
    /* 0x04 */  {"RLC H", NONE, false},
    /* 0x05 */  {"RLC L", NONE, false},
    /* 0x06 */  {"RLC (HL)", NONE, false},
    /* 0x07 */  {"RLC A", NONE, false},
    /* 0x08 */  {"RRC B", NONE, false},
    /* 0x09 */  {"RRC C", NONE, false},
    /* 0x0a */  {"RRC D", NONE, false},
    /* 0x0b */  {"RRC E", NONE, false},
    /* 0x0c */  {"RRC H", NONE, false},
    /* 0x0d */  {"RRC L", NONE, false},
    /* 0x0e */  {"RRC (HL)", NONE, false},
    /* 0x0f */  {"RRC A", NONE, false},
    /* 0x10 */  {"RL B", NONE, false},
    /* 0x11 */  {"RL C", NONE, false},
    /* 0x12 */  {"RL D", NONE, false},
    /* 0x13 */  {"RL E", NONE, false},
    /* 0x14 */  {"RL H", NONE, false},
    /* 0x15 */  {"RL L", NONE, false},
    /* 0x16 */  {"RL (HL)", NONE, false},
    /* 0x17 */  {"RL A", NONE, false},
    /* 0x18 */  {"RR B", NONE, false},
    /* 0x19 */  {"RR C", NONE, false},
    /* 0x1a */  {"RR D", NONE, false},
    /* 0x1b */  {"RR E", NONE, false},
    /* 0x1c */  {"RR H", NONE, false},
    /* 0x1d */  {"RR L", NONE, false},
    /* 0x1e */  {"RR (HL)", NONE, false},
    /* 0x1f */  {"RR A", NONE, false},
    /* 0x20 */  {"SLA B", NONE, false},
    /* 0x21 */  {"SLA C", NONE, false},
    /* 0x22 */  {"SLA D", NONE, false},
    /* 0x23 */  {"SLA E", NONE, false},
    /* 0x24 */  {"SLA H", NONE, false},
    /* 0x25 */  {"SLA L", NONE, false},
    /* 0x26 */  {"SLA (HL)", NONE, false},
    /* 0x27 */  {"SLA A", NONE, false},
    /* 0x28 */  {"SRA B", NONE, false},
    /* 0x29 */  {"SRA C", NONE, false},
    /* 0x2a */  {"SRA D", NONE, false},
    /* 0x2b */  {"SRA E", NONE, false},
    /* 0x2c */  {"SRA H", NONE, false},
    /* 0x2d */  {"SRA L", NONE, false},
    /* 0x2e */  {"SRA (HL)", NONE, false},
    /* 0x2f */  {"SRA A", NONE, false},
    /* 0x30 */  {"SLL B", NONE, true},
    /* 0x31 */  {"SLL C", NONE, true},
    /* 0x32 */  {"SLL D", NONE, true},
    /* 0x33 */  {"SLL E", NONE, true},
    /* 0x34 */  {"SLL H", NONE, true},
    /* 0x35 */  {"SLL L", NONE, true},
    /* 0x36 */  {"SLL (HL)", NONE, true},
    /* 0x37 */  {"SLL A", NONE, true},
    /* 0x38 */  {"SRL B", NONE, false},
    /* 0x39 */  {"SRL C", NONE, false},
    /* 0x3a */  {"SRL D", NONE, false},
    /* 0x3b */  {"SRL E", NONE, false},
    /* 0x3c */  {"SRL H", NONE, false},
    /* 0x3d */  {"SRL L", NONE, false},
    /* 0x3e */  {"SRL (HL)", NONE, false},
    /* 0x3f */  {"SRL A", NONE, false},
    /* 0x40 */  {"BIT 0, B", NONE, false},
    /* 0x41 */  {"BIT 0, C", NONE, false},
    /* 0x42 */  {"BIT 0, D", NONE, false},
    /* 0x43 */  {"BIT 0, E", NONE, false},
    /* 0x44 */  {"BIT 0, H", NONE, false},
    /* 0x45 */  {"BIT 0, L", NONE, false},
    /* 0x46 */  {"BIT 0, (HL)", NONE, false},
    /* 0x47 */  {"BIT 0, A", NONE, false},
    /* 0x48 */  {"BIT 1, B", NONE, false},
    /* 0x49 */  {"BIT 1, C", NONE, false},
    /* 0x4a */  {"BIT 1, D", NONE, false},
    /* 0x4b */  {"BIT 1, E", NONE, false},
    /* 0x4c */  {"BIT 1, H", NONE, false},
    /* 0x4d */  {"BIT 1, L", NONE, false},
    /* 0x4e */  {"BIT 1, (HL)", NONE, false},
    /* 0x4f */  {"BIT 1, A", NONE, false},
    /* 0x50 */  {"BIT 2, B", NONE, false},
    /* 0x51 */  {"BIT 2, C", NONE, false},
    /* 0x52 */  {"BIT 2, D", NONE, false},
    /* 0x53 */  {"BIT 2, E", NONE, false},
    /* 0x54 */  {"BIT 2, H", NONE, false},
    /* 0x55 */  {"BIT 2, L", NONE, false},
    /* 0x56 */  {"BIT 2, (HL)", NONE, false},
    /* 0x57 */  {"BIT 2, A", NONE, false},
    /* 0x58 */  {"BIT 3, B", NONE, false},
    /* 0x59 */  {"BIT 3, C", NONE, false},
    /* 0x5a */  {"BIT 3, D", NONE, false},
    /* 0x5b */  {"BIT 3, E", NONE, false},
    /* 0x5c */  {"BIT 3, H", NONE, false},
    /* 0x5d */  {"BIT 3, L", NONE, false},
    /* 0x5e */  {"BIT 3, (HL)", NONE, false},
    /* 0x5f */  {"BIT 3, A", NONE, false},
    /* 0x60 */  {"BIT 4, B", NONE, false},
    /* 0x61 */  {"BIT 4, C", NONE, false},
    /* 0x62 */  {"BIT 4, D", NONE, false},
    /* 0x63 */  {"BIT 4, E", NONE, false},
    /* 0x64 */  {"BIT 4, H", NONE, false},
    /* 0x65 */  {"BIT 4, L", NONE, false},
    /* 0x66 */  {"BIT 4, (HL)", NONE, false},
    /* 0x67 */  {"BIT 4, A", NONE, false},
    /* 0x68 */  {"BIT 5, B", NONE, false},
    /* 0x69 */  {"BIT 5, C", NONE, false},
    /* 0x6a */  {"BIT 5, D", NONE, false},
    /* 0x6b */  {"BIT 5, E", NONE, false},
    /* 0x6c */  {"BIT 5, H", NONE, false},
    /* 0x6d */  {"BIT 5, L", NONE, false},
    /* 0x6e */  {"BIT 5, (HL)", NONE, false},
    /* 0x6f */  {"BIT 5, A", NONE, false},
    /* 0x70 */  {"BIT 6, B", NONE, false},
    /* 0x71 */  {"BIT 6, C", NONE, false},
    /* 0x72 */  {"BIT 6, D", NONE, false},
    /* 0x73 */  {"BIT 6, E", NONE, false},
    /* 0x74 */  {"BIT 6, H", NONE, false},
    /* 0x75 */  {"BIT 6, L", NONE, false},
    /* 0x76 */  {"BIT 6, (HL)", NONE, false},
    /* 0x77 */  {"BIT 6, A", NONE, false},
    /* 0x78 */  {"BIT 7, B", NONE, false},
    /* 0x79 */  {"BIT 7, C", NONE, false},
    /* 0x7a */  {"BIT 7, D", NONE, false},
    /* 0x7b */  {"BIT 7, E", NONE, false},
    /* 0x7c */  {"BIT 7, H", NONE, false},
    /* 0x7d */  {"BIT 7, L", NONE, false},
    /* 0x7e */  {"BIT 7, (HL)", NONE, false},
    /* 0x7f */  {"BIT 7, A", NONE, false},
    /* 0x80 */  {"RES 0, B", NONE, false},
    /* 0x81 */  {"RES 0, C", NONE, false},
    /* 0x82 */  {"RES 0, D", NONE, false},
    /* 0x83 */  {"RES 0, E", NONE, false},
    /* 0x84 */  {"RES 0, H", NONE, false},
    /* 0x85 */  {"RES 0, L", NONE, false},
    /* 0x86 */  {"RES 0, (HL)", NONE, false},
    /* 0x87 */  {"RES 0, A", NONE, false},
    /* 0x88 */  {"RES 1, B", NONE, false},
    /* 0x89 */  {"RES 1, C", NONE, false},
    /* 0x8a */  {"RES 1, D", NONE, false},
    /* 0x8b */  {"RES 1, E", NONE, false},
    /* 0x8c */  {"RES 1, H", NONE, false},
    /* 0x8d */  {"RES 1, L", NONE, false},
    /* 0x8e */  {"RES 1, (HL)", NONE, false},
    /* 0x8f */  {"RES 1, A", NONE, false},
    /* 0x90 */  {"RES 2, B", NONE, false},
    /* 0x91 */  {"RES 2, C", NONE, false},
    /* 0x92 */  {"RES 2, D", NONE, false},
    /* 0x93 */  {"RES 2, E", NONE, false},
    /* 0x94 */  {"RES 2, H", NONE, false},
    /* 0x95 */  {"RES 2, L", NONE, false},
    /* 0x96 */  {"RES 2, (HL)", NONE, false},
    /* 0x97 */  {"RES 2, A", NONE, false},
    /* 0x98 */  {"RES 3, B", NONE, false},
    /* 0x99 */  {"RES 3, C", NONE, false},
    /* 0x9a */  {"RES 3, D", NONE, false},
    /* 0x9b */  {"RES 3, E", NONE, false},
    /* 0x9c */  {"RES 3, H", NONE, false},
    /* 0x9d */  {"RES 3, L", NONE, false},
    /* 0x9e */  {"RES 3, (HL)", NONE, false},
    /* 0x9f */  {"RES 3, A", NONE, false},
    /* 0xa0 */  {"RES 4, B", NONE, false},
    /* 0xa1 */  {"RES 4, C", NONE, false},
    /* 0xa2 */  {"RES 4, D", NONE, false},
    /* 0xa3 */  {"RES 4, E", NONE, false},
    /* 0xa4 */  {"RES 4, H", NONE, false},
    /* 0xa5 */  {"RES 4, L", NONE, false},
    /* 0xa6 */  {"RES 4, (HL)", NONE, false},
    /* 0xa7 */  {"RES 4, A", NONE, false},
    /* 0xa8 */  {"RES 5, B", NONE, false},
    /* 0xa9 */  {"RES 5, C", NONE, false},
    /* 0xaa */  {"RES 5, D", NONE, false},
    /* 0xab */  {"RES 5, E", NONE, false},
    /* 0xac */  {"RES 5, H", NONE, false},
    /* 0xad */  {"RES 5, L", NONE, false},
    /* 0xae */  {"RES 5, (HL)", NONE, false},
    /* 0xaf */  {"RES 5, A", NONE, false},
    /* 0xb0 */  {"RES 6, B", NONE, false},
    /* 0xb1 */  {"RES 6, C", NONE, false},
    /* 0xb2 */  {"RES 6, D", NONE, false},
    /* 0xb3 */  {"RES 6, E", NONE, false},
    /* 0xb4 */  {"RES 6, H", NONE, false},
    /* 0xb5 */  {"RES 6, L", NONE, false},
    /* 0xb6 */  {"RES 6, (HL)", NONE, false},
    /* 0xb7 */  {"RES 6, A", NONE, false},
    /* 0xb8 */  {"RES 7, B", NONE, false},
    /* 0xb9 */  {"RES 7, C", NONE, false},
    /* 0xba */  {"RES 7, D", NONE, false},
    /* 0xbb */  {"RES 7, E", NONE, false},
    /* 0xbc */  {"RES 7, H", NONE, false},
    /* 0xbd */  {"RES 7, L", NONE, false},
    /* 0xbe */  {"RES 7, (HL)", NONE, false},
    /* 0xbf */  {"RES 7, A", NONE, false},
    /* 0xc0 */  {"SET 0, B", NONE, false},
    /* 0xc1 */  {"SET 0, C", NONE, false},
    /* 0xc2 */  {"SET 0, D", NONE, false},
    /* 0xc3 */  {"SET 0, E", NONE, false},
    /* 0xc4 */  {"SET 0, H", NONE, false},
    /* 0xc5 */  {"SET 0, L", NONE, false},
    /* 0xc6 */  {"SET 0, (HL)", NONE, false},
    /* 0xc7 */  {"SET 0, A", NONE, false},
    /* 0xc8 */  {"SET 1, B", NONE, false},
    /* 0xc9 */  {"SET 1, C", NONE, false},
    /* 0xca */  {"SET 1, D", NONE, false},
    /* 0xcb */  {"SET 1, E", NONE, false},
    /* 0xcc */  {"SET 1, H", NONE, false},
    /* 0xcd */  {"SET 1, L", NONE, false},
    /* 0xce */  {"SET 1, (HL)", NONE, false},
    /* 0xcf */  {"SET 1, A", NONE, false},
    /* 0xd0 */  {"SET 2, B", NONE, false},
    /* 0xd1 */  {"SET 2, C", NONE, false},
    /* 0xd2 */  {"SET 2, D", NONE, false},
    /* 0xd3 */  {"SET 2, E", NONE, false},
    /* 0xd4 */  {"SET 2, H", NONE, false},
    /* 0xd5 */  {"SET 2, L", NONE, false},
    /* 0xd6 */  {"SET 2, (HL)", NONE, false},
    /* 0xd7 */  {"SET 2, A", NONE, false},
    /* 0xd8 */  {"SET 3, B", NONE, false},
    /* 0xd9 */  {"SET 3, C", NONE, false},
    /* 0xda */  {"SET 3, D", NONE, false},
    /* 0xdb */  {"SET 3, E", NONE, false},
    /* 0xdc */  {"SET 3, H", NONE, false},
    /* 0xdd */  {"SET 3, L", NONE, false},
    /* 0xde */  {"SET 3, (HL)", NONE, false},
    /* 0xdf */  {"SET 3, A", NONE, false},
    /* 0xe0 */  {"SET 4, B", NONE, false},
    /* 0xe1 */  {"SET 4, C", NONE, false},
    /* 0xe2 */  {"SET 4, D", NONE, false},
    /* 0xe3 */  {"SET 4, E", NONE, false},
    /* 0xe4 */  {"SET 4, H", NONE, false},
    /* 0xe5 */  {"SET 4, L", NONE, false},
    /* 0xe6 */  {"SET 4, (HL)", NONE, false},
    /* 0xe7 */  {"SET 4, A", NONE, false},
    /* 0xe8 */  {"SET 5, B", NONE, false},
    /* 0xe9 */  {"SET 5, C", NONE, false},
    /* 0xea */  {"SET 5, D", NONE, false},
    /* 0xeb */  {"SET 5, E", NONE, false},
    /* 0xec */  {"SET 5, H", NONE, false},
    /* 0xed */  {"SET 5, L", NONE, false},
    /* 0xee */  {"SET 5, (HL)", NONE, false},
    /* 0xef */  {"SET 5, A", NONE, false},
    /* 0xf0 */  {"SET 6, B", NONE, false},
    /* 0xf1 */  {"SET 6, C", NONE, false},
    /* 0xf2 */  {"SET 6, D", NONE, false},
    /* 0xf3 */  {"SET 6, E", NONE, false},
    /* 0xf4 */  {"SET 6, H", NONE, false},
    /* 0xf5 */  {"SET 6, L", NONE, false},
    /* 0xf6 */  {"SET 6, (HL)", NONE, false},
    /* 0xf7 */  {"SET 6, A", NONE, false},
    /* 0xf8 */  {"SET 7, B", NONE, false},
    /* 0xf9 */  {"SET 7, C", NONE, false},
    /* 0xfa */  {"SET 7, D", NONE, false},
    /* 0xfb */  {"SET 7, E", NONE, false},
    /* 0xfc */  {"SET 7, H", NONE, false},
    /* 0xfd */  {"SET 7, L", NONE, false},
    /* 0xfe */  {"SET 7, (HL)", NONE, false},
    /* 0xff */  {"SET 7, A", NONE, false},
};

InstrDesc opcodes_dd[256] = {
    /* 0x00 */  {"NOP", NONE, true},
    /* 0x01 */  {"LD BC, #%s", ABS16, true},
    /* 0x02 */  {"LD (BC),A", NONE, true},
    /* 0x03 */  {"INC BC", NONE, true},
    /* 0x04 */  {"INC B", NONE, true},
    /* 0x05 */  {"DEC B", NONE, true},
    /* 0x06 */  {"LD B, #%s", ABS8, true},
    /* 0x07 */  {"RLCA", NONE, true},
    /* 0x08 */  {"EX AF,AF'", NONE, true},
    /* 0x09 */  {"ADD IX,BC", NONE, false},
    /* 0x0a */  {"LD A,(BC)", NONE, true},
    /* 0x0b */  {"DEC BC", NONE, true},
    /* 0x0c */  {"INC C", NONE, true},
    /* 0x0d */  {"DEC C", NONE, true},
    /* 0x0e */  {"LD C, #%s", ABS8, true},
    /* 0x0f */  {"RRCA", NONE, true},
    /* 0x10 */  {"DJNZ %s", REL, true},
    /* 0x11 */  {"LD DE, #%s", ABS16, true},
    /* 0x12 */  {"LD (DE),A", NONE, true},
    /* 0x13 */  {"INC DE", NONE, true},
    /* 0x14 */  {"INC D", NONE, true},
    /* 0x15 */  {"DEC D", NONE, true},
    /* 0x16 */  {"LD D, #%s", ABS8, true},
    /* 0x17 */  {"RLA", NONE, true},
    /* 0x18 */  {"JR %s", REL, true},
    /* 0x19 */  {"ADD IX,DE", NONE, false},
    /* 0x1a */  {"LD A,(DE)", NONE, true},
    /* 0x1b */  {"DEC DE", NONE, true},
    /* 0x1c */  {"INC E", NONE, true},
    /* 0x1d */  {"DEC E", NONE, true},
    /* 0x1e */  {"LD E, #%s", ABS8, true},
    /* 0x1f */  {"RRA", NONE, true},
    /* 0x20 */  {"JR NZ, %s", REL, true},
    /* 0x21 */  {"LD IX, #%s", ABS16, false},
    /* 0x22 */  {"LD (%s),IX", ABS16, false},
    /* 0x23 */  {"INC IX", NONE, false},
    /* 0x24 */  {"INC IXH", NONE, true},
    /* 0x25 */  {"DEC IXH", NONE, true},
    /* 0x26 */  {"LD IXH, #%s", ABS8, true},
    /* 0x27 */  {"DAA", NONE, true},
    /* 0x28 */  {"JR Z, %s", REL, true},
    /* 0x29 */  {"ADD IX,IX", NONE, false},
    /* 0x2a */  {"LD IX, (%s)", ABS16, false},
    /* 0x2b */  {"DEC IX", NONE, false},
    /* 0x2c */  {"INC IXL", NONE, true},
    /* 0x2d */  {"DEC IXL", NONE, true},
    /* 0x2e */  {"LD IXL, #%s", ABS8, true},
    /* 0x2f */  {"CPL", NONE, true},
    /* 0x30 */  {"JR NC, %s", REL, true},
    /* 0x31 */  {"LD SP, #%s", ABS16, true},
    /* 0x32 */  {"LD (%s),A", ABS16, true},
    /* 0x33 */  {"INC SP", NONE, true},
    /* 0x34 */  {"INC (IX%s)", DISP, false},
    /* 0x35 */  {"DEC (IX%s)", DISP, false},
    /* 0x36 */  {"LD (IX%s), #%s", DISP_ABS8, false},
    /* 0x37 */  {"SCF", NONE, true},
    /* 0x38 */  {"JR C, %s", REL, true},
    /* 0x39 */  {"ADD IX,SP", NONE, false},
    /* 0x3a */  {"LD A, (%s)", ABS16, true},
    /* 0x3b */  {"DEC SP", NONE, true},
    /* 0x3c */  {"INC A", NONE, true},
    /* 0x3d */  {"DEC A", NONE, true},
    /* 0x3e */  {"LD A, #%s", ABS8, true},
    /* 0x3f */  {"CCF", NONE, true},
    /* 0x40 */  {"LD B,B", NONE, true},
    /* 0x41 */  {"LD B,C", NONE, true},
    /* 0x42 */  {"LD B,D", NONE, true},
    /* 0x43 */  {"LD B,E", NONE, true},
    /* 0x44 */  {"LD B,IXH", NONE, true},
    /* 0x45 */  {"LD B,IXL", NONE, true},
    /* 0x46 */  {"LD B, (IX%s)", DISP, false},
    /* 0x47 */  {"LD B,A", NONE, true},
    /* 0x48 */  {"LD C,B", NONE, true},
    /* 0x49 */  {"LD C,C", NONE, true},
    /* 0x4a */  {"LD C,D", NONE, true},
    /* 0x4b */  {"LD C,E", NONE, true},
    /* 0x4c */  {"LD C,IXH", NONE, true},
    /* 0x4d */  {"LD C,IXL", NONE, true},
    /* 0x4e */  {"LD C, (IX%s)", DISP, false},
    /* 0x4f */  {"LD C,A", NONE, true},
    /* 0x50 */  {"LD D,B", NONE, true},
    /* 0x51 */  {"LD D,C", NONE, true},
    /* 0x52 */  {"LD D,D", NONE, true},
    /* 0x53 */  {"LD D,E", NONE, true},
    /* 0x54 */  {"LD D,IXH", NONE, true},
    /* 0x55 */  {"LD D,IXL", NONE, true},
    /* 0x56 */  {"LD D, (IX%s)", DISP, false},
    /* 0x57 */  {"LD D,A", NONE, true},
    /* 0x58 */  {"LD E,B", NONE, true},
    /* 0x59 */  {"LD E,C", NONE, true},
    /* 0x5a */  {"LD E,D", NONE, true},
    /* 0x5b */  {"LD E,E", NONE, true},
    /* 0x5c */  {"LD E,IXH", NONE, true},
    /* 0x5d */  {"LD E,IXL", NONE, true},
    /* 0x5e */  {"LD E, (IX%s)", DISP, false},
    /* 0x5f */  {"LD E,A", NONE, true},
    /* 0x60 */  {"LD IXH,B", NONE, true},
    /* 0x61 */  {"LD IXH,C", NONE, true},
    /* 0x62 */  {"LD IXH,D", NONE, true},
    /* 0x63 */  {"LD IXH,E", NONE, true},
    /* 0x64 */  {"LD IXH,IXH", NONE, true},
    /* 0x65 */  {"LD IXH,IXL", NONE, true},
    /* 0x66 */  {"LD H, (IX%s)", DISP, false},
    /* 0x67 */  {"LD IXH,A", NONE, true},
    /* 0x68 */  {"LD IXL,B", NONE, true},
    /* 0x69 */  {"LD IXL,C", NONE, true},
    /* 0x6a */  {"LD IXL,D", NONE, true},
    /* 0x6b */  {"LD IXL,E", NONE, true},
    /* 0x6c */  {"LD IXL,IXH", NONE, true},
    /* 0x6d */  {"LD IXL,IXL", NONE, true},
    /* 0x6e */  {"LD L, (IX%s)", DISP, false},
    /* 0x6f */  {"LD IXL,A", NONE, true},
    /* 0x70 */  {"LD (IX%s), B", DISP, false},
    /* 0x71 */  {"LD (IX%s), C", DISP, false},
    /* 0x72 */  {"LD (IX%s), D", DISP, false},
    /* 0x73 */  {"LD (IX%s), E", DISP, false},
    /* 0x74 */  {"LD (IX%s), H", DISP, false},
    /* 0x75 */  {"LD (IX%s), L", DISP, false},
    /* 0x76 */  {"HALT", NONE, true},
    /* 0x77 */  {"LD (IX%s), A", DISP, false},
    /* 0x78 */  {"LD A,B", NONE, true},
    /* 0x79 */  {"LD A,C", NONE, true},
    /* 0x7a */  {"LD A,D", NONE, true},
    /* 0x7b */  {"LD A,E", NONE, true},
    /* 0x7c */  {"LD A,IXH", NONE, true},
    /* 0x7d */  {"LD A,IXL", NONE, true},
    /* 0x7e */  {"LD A, (IX%s)", DISP, false},
    /* 0x7f */  {"LD A,A", NONE, true},
    /* 0x80 */  {"ADD B", NONE, true},
    /* 0x81 */  {"ADD C", NONE, true},
    /* 0x82 */  {"ADD D", NONE, true},
    /* 0x83 */  {"ADD E", NONE, true},
    /* 0x84 */  {"ADD IXH", NONE, true},
    /* 0x85 */  {"ADD IXL", NONE, true},
    /* 0x86 */  {"ADD (IX%s)", DISP, false},
    /* 0x87 */  {"ADD A", NONE, true},
    /* 0x88 */  {"ADC B", NONE, true},
    /* 0x89 */  {"ADC C", NONE, true},
    /* 0x8a */  {"ADC D", NONE, true},
    /* 0x8b */  {"ADC E", NONE, true},
    /* 0x8c */  {"ADC IXH", NONE, true},
    /* 0x8d */  {"ADC IXL", NONE, true},
    /* 0x8e */  {"ADC (IX%s)", DISP, false},
    /* 0x8f */  {"ADC A", NONE, true},
    /* 0x90 */  {"SUB B", NONE, true},
    /* 0x91 */  {"SUB C", NONE, true},
    /* 0x92 */  {"SUB D", NONE, true},
    /* 0x93 */  {"SUB E", NONE, true},
    /* 0x94 */  {"SUB IXH", NONE, true},
    /* 0x95 */  {"SUB IXL", NONE, true},
    /* 0x96 */  {"SUB (IX%s)", DISP, false},
    /* 0x97 */  {"SUB A", NONE, true},
    /* 0x98 */  {"SBC B", NONE, true},
    /* 0x99 */  {"SBC C", NONE, true},
    /* 0x9a */  {"SBC D", NONE, true},
    /* 0x9b */  {"SBC E", NONE, true},
    /* 0x9c */  {"SBC IXH", NONE, true},
    /* 0x9d */  {"SBC IXL", NONE, true},
    /* 0x9e */  {"SBC (IX%s)", DISP, false},
    /* 0x9f */  {"SBC A", NONE, true},
    /* 0xa0 */  {"AND B", NONE, true},
    /* 0xa1 */  {"AND C", NONE, true},
    /* 0xa2 */  {"AND D", NONE, true},
    /* 0xa3 */  {"AND E", NONE, true},
    /* 0xa4 */  {"AND IXH", NONE, true},
    /* 0xa5 */  {"AND IXL", NONE, true},
    /* 0xa6 */  {"AND (IX%s)", DISP, false},
    /* 0xa7 */  {"AND A", NONE, true},
    /* 0xa8 */  {"XOR B", NONE, true},
    /* 0xa9 */  {"XOR C", NONE, true},
    /* 0xaa */  {"XOR D", NONE, true},
    /* 0xab */  {"XOR E", NONE, true},
    /* 0xac */  {"XOR IXH", NONE, true},
    /* 0xad */  {"XOR IXL", NONE, true},
    /* 0xae */  {"XOR (IX%s)", DISP, false},
    /* 0xaf */  {"XOR A", NONE, true},
    /* 0xb0 */  {"OR B", NONE, true},
    /* 0xb1 */  {"OR C", NONE, true},
    /* 0xb2 */  {"OR D", NONE, true},
    /* 0xb3 */  {"OR E", NONE, true},
    /* 0xb4 */  {"OR IXH", NONE, true},
    /* 0xb5 */  {"OR IXL", NONE, true},
    /* 0xb6 */  {"OR (IX%s)", DISP, false},
    /* 0xb7 */  {"OR A", NONE, true},
    /* 0xb8 */  {"CP B", NONE, true},
    /* 0xb9 */  {"CP C", NONE, true},
    /* 0xba */  {"CP D", NONE, true},
    /* 0xbb */  {"CP E", NONE, true},
    /* 0xbc */  {"CP IXH", NONE, true},
    /* 0xbd */  {"CP IXL", NONE, true},
    /* 0xbe */  {"CP (IX%s)", DISP, false},
    /* 0xbf */  {"CP A", NONE, true},
    /* 0xc0 */  {"RET NZ", NONE, true},
    /* 0xc1 */  {"POP BC", NONE, true},
    /* 0xc2 */  {"JP NZ, %s", ABS16, true},
    /* 0xc3 */  {"JP %s", ABS16, true},
    /* 0xc4 */  {"CALL NZ, %s", ABS16, true},
    /* 0xc5 */  {"PUSH BC", NONE, true},
    /* 0xc6 */  {"ADD #%s", ABS8, true},
    /* 0xc7 */  {"RST 00", NONE, true},
    /* 0xc8 */  {"RET Z", NONE, true},
    /* 0xc9 */  {"RET", NONE, true},
    /* 0xca */  {"JP Z, %s", ABS16, true},
    /* 0xcb */  {"???", NONE, true},
    /* 0xcc */  {"CALL Z, %s", ABS16, true},
    /* 0xcd */  {"CALL %s", ABS16, true},
    /* 0xce */  {"ADC #%s", ABS8, true},
    /* 0xcf */  {"RST 08", NONE, true},
    /* 0xd0 */  {"RET NC", NONE, true},
    /* 0xd1 */  {"POP DE", NONE, true},
    /* 0xd2 */  {"JP NC, %s", ABS16, true},
    /* 0xd3 */  {"OUTA %s", ABS8, true},
    /* 0xd4 */  {"CALL NC, %s", ABS16, true},
    /* 0xd5 */  {"PUSH DE", NONE, true},
    /* 0xd6 */  {"SUB #%s", ABS8, true},
    /* 0xd7 */  {"RST 10", NONE, true},
    /* 0xd8 */  {"RET C", NONE, true},
    /* 0xd9 */  {"EXX", NONE, true},
    /* 0xda */  {"JP C, %s", ABS16, true},
    /* 0xdb */  {"INA %s", ABS8, true},
    /* 0xdc */  {"CALL C, %s", ABS16, true},
    /* 0xdd */  {"NOP #%s", ABS8, true},
    /* 0xde */  {"SBC #%s", ABS8, true},
    /* 0xdf */  {"RST 18", NONE, true},
    /* 0xe0 */  {"RET PO", NONE, true},
    /* 0xe1 */  {"POP IX", NONE, false},
    /* 0xe2 */  {"JP PO, %s", ABS16, true},
    /* 0xe3 */  {"EX (SP),IX", NONE, false},
    /* 0xe4 */  {"CALL PO, %s", ABS16, true},
    /* 0xe5 */  {"PUSH IX", NONE, false},
    /* 0xe6 */  {"AND #%s", ABS8, true},
    /* 0xe7 */  {"RST 20", NONE, true},
    /* 0xe8 */  {"RET PE", NONE, true},
    /* 0xe9 */  {"JP (IX)", NONE, false},
    /* 0xea */  {"JP PE, %s", ABS16, true},
    /* 0xeb */  {"EX DE,HL", NONE, true},
    /* 0xec */  {"CALL PE, %s", ABS16, true},
    /* 0xed */  {"PFX_DDED #%s", ABS8, true},
    /* 0xee */  {"XOR #%s", ABS8, true},
    /* 0xef */  {"RST 28", NONE, true},
    /* 0xf0 */  {"RET P", NONE, true},
    /* 0xf1 */  {"POP AF", NONE, true},
    /* 0xf2 */  {"JP P, %s", ABS16, true},
    /* 0xf3 */  {"DI", NONE, true},
    /* 0xf4 */  {"CALL P, %s", ABS16, true},
    /* 0xf5 */  {"PUSH AF", NONE, true},
    /* 0xf6 */  {"OR #%s", ABS8, true},
    /* 0xf7 */  {"RST 30", NONE, true},
    /* 0xf8 */  {"RET M", NONE, true},
    /* 0xf9 */  {"LD SP,IX", NONE, false},
    /* 0xfa */  {"JP M, %s", ABS16, true},
    /* 0xfb */  {"EI", NONE, true},
    /* 0xfc */  {"CALL M, %s", ABS16, true},
    /* 0xfd */  {"NOP #%s", ABS8, true},
    /* 0xfe */  {"CP #%s", ABS8, true},
    /* 0xff */  {"RST 38", NONE, true},
};

InstrDesc opcodes_ed[256] = {
    /* 0x00 */  {"NOP", NONE, true},
    /* 0x01 */  {"???", NONE, true},
    /* 0x02 */  {"???", NONE, true},
    /* 0x03 */  {"???", NONE, true},
    /* 0x04 */  {"???", NONE, true},
    /* 0x05 */  {"???", NONE, true},
    /* 0x06 */  {"???", NONE, true},
    /* 0x07 */  {"???", NONE, true},
    /* 0x08 */  {"???", NONE, true},
    /* 0x09 */  {"???", NONE, true},
    /* 0x0a */  {"???", NONE, true},
    /* 0x0b */  {"???", NONE, true},
    /* 0x0c */  {"???", NONE, true},
    /* 0x0d */  {"???", NONE, true},
    /* 0x0e */  {"???", NONE, true},
    /* 0x0f */  {"???", NONE, true},
    /* 0x10 */  {"???", NONE, true},
    /* 0x11 */  {"???", NONE, true},
    /* 0x12 */  {"???", NONE, true},
    /* 0x13 */  {"???", NONE, true},
    /* 0x14 */  {"???", NONE, true},
    /* 0x15 */  {"???", NONE, true},
    /* 0x16 */  {"???", NONE, true},
    /* 0x17 */  {"???", NONE, true},
    /* 0x18 */  {"???", NONE, true},
    /* 0x19 */  {"???", NONE, true},
    /* 0x1a */  {"???", NONE, true},
    /* 0x1b */  {"???", NONE, true},
    /* 0x1c */  {"???", NONE, true},
    /* 0x1d */  {"???", NONE, true},
    /* 0x1e */  {"???", NONE, true},
    /* 0x1f */  {"???", NONE, true},
    /* 0x20 */  {"???", NONE, true},
    /* 0x21 */  {"???", NONE, true},
    /* 0x22 */  {"???", NONE, true},
    /* 0x23 */  {"???", NONE, true},
    /* 0x24 */  {"???", NONE, true},
    /* 0x25 */  {"???", NONE, true},
    /* 0x26 */  {"???", NONE, true},
    /* 0x27 */  {"???", NONE, true},
    /* 0x28 */  {"???", NONE, true},
    /* 0x29 */  {"???", NONE, true},
    /* 0x2a */  {"???", NONE, true},
    /* 0x2b */  {"???", NONE, true},
    /* 0x2c */  {"???", NONE, true},
    /* 0x2d */  {"???", NONE, true},
    /* 0x2e */  {"???", NONE, true},
    /* 0x2f */  {"???", NONE, true},
    /* 0x30 */  {"???", NONE, true},
    /* 0x31 */  {"???", NONE, true},
    /* 0x32 */  {"???", NONE, true},
    /* 0x33 */  {"???", NONE, true},
    /* 0x34 */  {"???", NONE, true},
    /* 0x35 */  {"???", NONE, true},
    /* 0x36 */  {"???", NONE, true},
    /* 0x37 */  {"???", NONE, true},
    /* 0x38 */  {"???", NONE, true},
    /* 0x39 */  {"???", NONE, true},
    /* 0x3a */  {"???", NONE, true},
    /* 0x3b */  {"???", NONE, true},
    /* 0x3c */  {"???", NONE, true},
    /* 0x3d */  {"???", NONE, true},
    /* 0x3e */  {"???", NONE, true},
    /* 0x3f */  {"???", NONE, true},
    /* 0x40 */  {"IN B,(C)", NONE, false},
    /* 0x41 */  {"OUT (C),B", NONE, false},
    /* 0x42 */  {"SBC HL,BC", NONE, false},
    /* 0x43 */  {"LD (%s),BC", ABS16, false},
    /* 0x44 */  {"NEG", NONE, false},
    /* 0x45 */  {"RETN", NONE, false},
    /* 0x46 */  {"IM 0", NONE, false},
    /* 0x47 */  {"LD I,A", NONE, false},
    /* 0x48 */  {"IN C,(C)", NONE, false},
    /* 0x49 */  {"OUT (C),C", NONE, false},
    /* 0x4a */  {"ADC HL,BC", NONE, false},
    /* 0x4b */  {"LD BC, (%s)", ABS16, false},
    /* 0x4c */  {"NEG", NONE, true},
    /* 0x4d */  {"RETI", NONE, false},
    /* 0x4e */  {"IM 0/1", NONE, true},
    /* 0x4f */  {"LD R,A", NONE, false},
    /* 0x50 */  {"IN D,(C)", NONE, false},
    /* 0x51 */  {"OUT (C),D", NONE, false},
    /* 0x52 */  {"SBC HL,DE", NONE, false},
    /* 0x53 */  {"LD (%s),DE", ABS16, false},
    /* 0x54 */  {"NEG", NONE, true},
    /* 0x55 */  {"RETN", NONE, false},
    /* 0x56 */  {"IM 1", NONE, false},
    /* 0x57 */  {"LD A,I", NONE, false},
    /* 0x58 */  {"IN E,(C)", NONE, false},
    /* 0x59 */  {"OUT (C),E", NONE, false},
    /* 0x5a */  {"ADC HL,DE", NONE, false},
    /* 0x5b */  {"LD DE, (%s)", ABS16, false},
    /* 0x5c */  {"NEG", NONE, true},
    /* 0x5d */  {"RETN", NONE, false},
    /* 0x5e */  {"IM 2", NONE, false},
    /* 0x5f */  {"LD A,R", NONE, false},
    /* 0x60 */  {"IN H,(C)", NONE, false},
    /* 0x61 */  {"OUT (C),H", NONE, false},
    /* 0x62 */  {"SBC HL,HL", NONE, false},
    /* 0x63 */  {"LD (%s),HL", ABS16, true},
    /* 0x64 */  {"NEG", NONE, true},
    /* 0x65 */  {"RETN", NONE, false},
    /* 0x66 */  {"IM 0", NONE, false},
    /* 0x67 */  {"RRD", NONE, false},
    /* 0x68 */  {"IN L,(C)", NONE, false},
    /* 0x69 */  {"OUT (C),L", NONE, false},
    /* 0x6a */  {"ADC HL,HL", NONE, false},
    /* 0x6b */  {"LD HL, (%s)", ABS16, true},
    /* 0x6c */  {"NEG", NONE, true},
    /* 0x6d */  {"RETN", NONE, false},
    /* 0x6e */  {"IM 0/1", NONE, true},
    /* 0x6f */  {"RLD", NONE, false},
    /* 0x70 */  {"IN (C)", NONE, true},
    /* 0x71 */  {"OUT (C), 0", NONE, true},
    /* 0x72 */  {"SBC HL,SP", NONE, false},
    /* 0x73 */  {"LD (%s),SP", ABS16, false},
    /* 0x74 */  {"NEG", NONE, true},
    /* 0x75 */  {"RETN", NONE, false},
    /* 0x76 */  {"IM 1", NONE, false},
    /* 0x77 */  {"NOP", NONE, true},
    /* 0x78 */  {"IN A,(C)", NONE, false},
    /* 0x79 */  {"OUT (C),A", NONE, false},
    /* 0x7a */  {"ADC HL,SP", NONE, false},
    /* 0x7b */  {"LD SP, (%s)", ABS16, false},
    /* 0x7c */  {"NEG", NONE, true},
    /* 0x7d */  {"RETN", NONE, false},
    /* 0x7e */  {"IM 2", NONE, false},
    /* 0x7f */  {"NOP", NONE, true},
    /* 0x80 */  {"???", NONE, true},
    /* 0x81 */  {"???", NONE, true},
    /* 0x82 */  {"???", NONE, true},
    /* 0x83 */  {"???", NONE, true},
    /* 0x84 */  {"???", NONE, true},
    /* 0x85 */  {"???", NONE, true},
    /* 0x86 */  {"???", NONE, true},
    /* 0x87 */  {"???", NONE, true},
    /* 0x88 */  {"???", NONE, true},
    /* 0x89 */  {"???", NONE, true},
    /* 0x8a */  {"???", NONE, true},
    /* 0x8b */  {"???", NONE, true},
    /* 0x8c */  {"???", NONE, true},
    /* 0x8d */  {"???", NONE, true},
    /* 0x8e */  {"???", NONE, true},
    /* 0x8f */  {"???", NONE, true},
    /* 0x90 */  {"???", NONE, true},
    /* 0x91 */  {"???", NONE, true},
    /* 0x92 */  {"???", NONE, true},
    /* 0x93 */  {"???", NONE, true},
    /* 0x94 */  {"???", NONE, true},
    /* 0x95 */  {"???", NONE, true},
    /* 0x96 */  {"???", NONE, true},
    /* 0x97 */  {"???", NONE, true},
    /* 0x98 */  {"???", NONE, true},
    /* 0x99 */  {"???", NONE, true},
    /* 0x9a */  {"???", NONE, true},
    /* 0x9b */  {"???", NONE, true},
    /* 0x9c */  {"???", NONE, true},
    /* 0x9d */  {"???", NONE, true},
    /* 0x9e */  {"???", NONE, true},
    /* 0x9f */  {"???", NONE, true},
    /* 0xa0 */  {"LDI", NONE, false},
    /* 0xa1 */  {"CPI", NONE, false},
    /* 0xa2 */  {"INI", NONE, false},
    /* 0xa3 */  {"OUTI", NONE, false},
    /* 0xa4 */  {"???", NONE, true},
    /* 0xa5 */  {"???", NONE, true},
    /* 0xa6 */  {"???", NONE, true},
    /* 0xa7 */  {"???", NONE, true},
    /* 0xa8 */  {"LDD", NONE, false},
    /* 0xa9 */  {"CPD", NONE, false},
    /* 0xaa */  {"IND", NONE, false},
    /* 0xab */  {"OUTD", NONE, false},
    /* 0xac */  {"???", NONE, true},
    /* 0xad */  {"???", NONE, true},
    /* 0xae */  {"???", NONE, true},
    /* 0xaf */  {"???", NONE, true},
    /* 0xb0 */  {"LDIR", NONE, false},
    /* 0xb1 */  {"CPIR", NONE, false},
    /* 0xb2 */  {"INIR", NONE, false},
    /* 0xb3 */  {"OTIR", NONE, false},
    /* 0xb4 */  {"???", NONE, true},
    /* 0xb5 */  {"???", NONE, true},
    /* 0xb6 */  {"???", NONE, true},
    /* 0xb7 */  {"???", NONE, true},
    /* 0xb8 */  {"LDDR", NONE, false},
    /* 0xb9 */  {"CPDR", NONE, false},
    /* 0xba */  {"INDR", NONE, false},
    /* 0xbb */  {"OTDR", NONE, false},
    /* 0xbc */  {"???", NONE, true},
    /* 0xbd */  {"???", NONE, true},
    /* 0xbe */  {"???", NONE, true},
    /* 0xbf */  {"???", NONE, true},
    /* 0xc0 */  {"???", NONE, true},
    /* 0xc1 */  {"???", NONE, true},
    /* 0xc2 */  {"???", NONE, true},
    /* 0xc3 */  {"???", NONE, true},
    /* 0xc4 */  {"???", NONE, true},
    /* 0xc5 */  {"???", NONE, true},
    /* 0xc6 */  {"???", NONE, true},
    /* 0xc7 */  {"???", NONE, true},
    /* 0xc8 */  {"???", NONE, true},
    /* 0xc9 */  {"???", NONE, true},
    /* 0xca */  {"???", NONE, true},
    /* 0xcb */  {"NOP", NONE, true},
    /* 0xcc */  {"???", NONE, true},
    /* 0xcd */  {"???", NONE, true},
    /* 0xce */  {"???", NONE, true},
    /* 0xcf */  {"???", NONE, true},
    /* 0xd0 */  {"???", NONE, true},
    /* 0xd1 */  {"???", NONE, true},
    /* 0xd2 */  {"???", NONE, true},
    /* 0xd3 */  {"???", NONE, true},
    /* 0xd4 */  {"???", NONE, true},
    /* 0xd5 */  {"???", NONE, true},
    /* 0xd6 */  {"???", NONE, true},
    /* 0xd7 */  {"???", NONE, true},
    /* 0xd8 */  {"???", NONE, true},
    /* 0xd9 */  {"???", NONE, true},
    /* 0xda */  {"???", NONE, true},
    /* 0xdb */  {"???", NONE, true},
    /* 0xdc */  {"???", NONE, true},
    /* 0xdd */  {"NOP", NONE, true},
    /* 0xde */  {"???", NONE, true},
    /* 0xdf */  {"???", NONE, true},
    /* 0xe0 */  {"???", NONE, true},
    /* 0xe1 */  {"???", NONE, true},
    /* 0xe2 */  {"???", NONE, true},
    /* 0xe3 */  {"???", NONE, true},
    /* 0xe4 */  {"???", NONE, true},
    /* 0xe5 */  {"???", NONE, true},
    /* 0xe6 */  {"???", NONE, true},
    /* 0xe7 */  {"???", NONE, true},
    /* 0xe8 */  {"???", NONE, true},
    /* 0xe9 */  {"???", NONE, true},
    /* 0xea */  {"???", NONE, true},
    /* 0xeb */  {"???", NONE, true},
    /* 0xec */  {"???", NONE, true},
    /* 0xed */  {"NOP", NONE, true},
    /* 0xee */  {"???", NONE, true},
    /* 0xef */  {"???", NONE, true},
    /* 0xf0 */  {"???", NONE, true},
    /* 0xf1 */  {"???", NONE, true},
    /* 0xf2 */  {"???", NONE, true},
    /* 0xf3 */  {"???", NONE, true},
    /* 0xf4 */  {"???", NONE, true},
    /* 0xf5 */  {"???", NONE, true},
    /* 0xf6 */  {"???", NONE, true},
    /* 0xf7 */  {"???", NONE, true},
    /* 0xf8 */  {"???", NONE, true},
    /* 0xf9 */  {"???", NONE, true},
    /* 0xfa */  {"???", NONE, true},
    /* 0xfb */  {"???", NONE, true},
    /* 0xfc */  {"???", NONE, true},
    /* 0xfd */  {"NOP", NONE, true},
    /* 0xfe */  {"???", NONE, true},
    /* 0xff */  {"???", NONE, true},
};

InstrDesc opcodes_fd[256] = {
  /* 0x00 */  {"NOP", NONE, true},
  /* 0x01 */  {"LD BC, #%s", ABS16, true},
  /* 0x02 */  {"LD (BC),A", NONE, true},
  /* 0x03 */  {"INC BC", NONE, true},
  /* 0x04 */  {"INC B", NONE, true},
  /* 0x05 */  {"DEC B", NONE, true},
  /* 0x06 */  {"LD B, #%s", ABS8, true},
  /* 0x07 */  {"RLCA", NONE, true},
  /* 0x08 */  {"EX AF,AF'", NONE, true},
  /* 0x09 */  {"ADD IY,BC", NONE, false},
  /* 0x0a */  {"LD A,(BC)", NONE, true},
  /* 0x0b */  {"DEC BC", NONE, true},
  /* 0x0c */  {"INC C", NONE, true},
  /* 0x0d */  {"DEC C", NONE, true},
  /* 0x0e */  {"LD C, #%s", ABS8, true},
  /* 0x0f */  {"RRCA", NONE, true},
  /* 0x10 */  {"DJNZ %s", REL, true},
  /* 0x11 */  {"LD DE, #%s", ABS16, true},
  /* 0x12 */  {"LD (DE),A", NONE, true},
  /* 0x13 */  {"INC DE", NONE, true},
  /* 0x14 */  {"INC D", NONE, true},
  /* 0x15 */  {"DEC D", NONE, true},
  /* 0x16 */  {"LD D, #%s", ABS8, true},
  /* 0x17 */  {"RLA", NONE, true},
  /* 0x18 */  {"JR %s", REL, true},
  /* 0x19 */  {"ADD IY,DE", NONE, false},
  /* 0x1a */  {"LD A,(DE)", NONE, true},
  /* 0x1b */  {"DEC DE", NONE, true},
  /* 0x1c */  {"INC E", NONE, true},
  /* 0x1d */  {"DEC E", NONE, true},
  /* 0x1e */  {"LD E, #%s", ABS8, true},
  /* 0x1f */  {"RRA", NONE, true},
  /* 0x20 */  {"JR NZ, %s", REL, true},
  /* 0x21 */  {"LD IY, #%s", ABS16, false},
  /* 0x22 */  {"LD (%s),IY", ABS16, false},
  /* 0x23 */  {"INC IY", NONE, false},
  /* 0x24 */  {"INC IYH", NONE, true},
  /* 0x25 */  {"DEC IYH", NONE, true},
  /* 0x26 */  {"LD IYH, #%s", ABS8, true},
  /* 0x27 */  {"DAA", NONE, true},
  /* 0x28 */  {"JR Z, %s", REL, true},
  /* 0x29 */  {"ADD IY,IY", NONE, false},
  /* 0x2a */  {"LD IY, (%s)", ABS16, false},
  /* 0x2b */  {"DEC IY", NONE, false},
  /* 0x2c */  {"INC IYL", NONE, true},
  /* 0x2d */  {"DEC IYL", NONE, true},
  /* 0x2e */  {"LD IYL, #%s", ABS8, true},
  /* 0x2f */  {"CPL", NONE, true},
  /* 0x30 */  {"JR NC, %s", REL, true},
  /* 0x31 */  {"LD SP, #%s", ABS16, true},
  /* 0x32 */  {"LD (%s),A", ABS16, true},
  /* 0x33 */  {"INC SP", NONE, true},
  /* 0x34 */  {"INC (IY%s)", DISP, false},
  /* 0x35 */  {"DEC (IY%s)", DISP, false},
  /* 0x36 */  {"LD (IY%s), #%s", DISP_ABS8, false},
  /* 0x37 */  {"SCF", NONE, true},
  /* 0x38 */  {"JR C, %s", REL, true},
  /* 0x39 */  {"ADD IY,SP", NONE, false},
  /* 0x3a */  {"LD A, (%s)", ABS16, true},
  /* 0x3b */  {"DEC SP", NONE, true},
  /* 0x3c */  {"INC A", NONE, true},
  /* 0x3d */  {"DEC A", NONE, true},
  /* 0x3e */  {"LD A, #%s", ABS8, true},
  /* 0x3f */  {"CCF", NONE, true},
  /* 0x40 */  {"LD B,B", NONE, true},
  /* 0x41 */  {"LD B,C", NONE, true},
  /* 0x42 */  {"LD B,D", NONE, true},
  /* 0x43 */  {"LD B,E", NONE, true},
  /* 0x44 */  {"LD B,IYH", NONE, true},
  /* 0x45 */  {"LD B,IYL", NONE, true},
  /* 0x46 */  {"LD B, (IY%s)", DISP, false},
  /* 0x47 */  {"LD B,A", NONE, true},
  /* 0x48 */  {"LD C,B", NONE, true},
  /* 0x49 */  {"LD C,C", NONE, true},
  /* 0x4a */  {"LD C,D", NONE, true},
  /* 0x4b */  {"LD C,E", NONE, true},
  /* 0x4c */  {"LD C,IYH", NONE, true},
  /* 0x4d */  {"LD C,IYL", NONE, true},
  /* 0x4e */  {"LD C, (IY%s)", DISP, false},
  /* 0x4f */  {"LD C,A", NONE, true},
  /* 0x50 */  {"LD D,B", NONE, true},
  /* 0x51 */  {"LD D,C", NONE, true},
  /* 0x52 */  {"LD D,D", NONE, true},
  /* 0x53 */  {"LD D,E", NONE, true},
  /* 0x54 */  {"LD D,IYH", NONE, true},
  /* 0x55 */  {"LD D,IY", NONE, true},
  /* 0x56 */  {"LD D, (IY%s)", DISP, false},
  /* 0x57 */  {"LD D,A", NONE, true},
  /* 0x58 */  {"LD E,B", NONE, true},
  /* 0x59 */  {"LD E,C", NONE, true},
  /* 0x5a */  {"LD E,D", NONE, true},
  /* 0x5b */  {"LD E,E", NONE, true},
  /* 0x5c */  {"LD E,IYH", NONE, true},
  /* 0x5d */  {"LD E,IYL", NONE, true},
  /* 0x5e */  {"LD E, (IY%s)", DISP, false},
  /* 0x5f */  {"LD E,A", NONE, true},
  /* 0x60 */  {"LD IYH,B", NONE, true},
  /* 0x61 */  {"LD IYH,C", NONE, true},
  /* 0x62 */  {"LD IYH,D", NONE, true},
  /* 0x63 */  {"LD IYH,E", NONE, true},
  /* 0x64 */  {"LD IYH,IYH", NONE, true},
  /* 0x65 */  {"LD IYH,IYL", NONE, true},
  /* 0x66 */  {"LD H, (IY%s)", DISP, false},
  /* 0x67 */  {"LD IYH,A", NONE, true},
  /* 0x68 */  {"LD IYL,B", NONE, true},
  /* 0x69 */  {"LD IYL,C", NONE, true},
  /* 0x6a */  {"LD IYL,D", NONE, true},
  /* 0x6b */  {"LD IYL,E", NONE, true},
  /* 0x6c */  {"LD IYL,IYH", NONE, true},
  /* 0x6d */  {"LD IYL,IYL", NONE, true},
  /* 0x6e */  {"LD L, (IY%s)", DISP, false},
  /* 0x6f */  {"LD IYL,A", NONE, true},
  /* 0x70 */  {"LD (IY%s), B", DISP, false},
  /* 0x71 */  {"LD (IY%s), C", DISP, false},
  /* 0x72 */  {"LD (IY%s), D", DISP, false},
  /* 0x73 */  {"LD (IY%s), E", DISP, false},
  /* 0x74 */  {"LD (IY%s), H", DISP, false},
  /* 0x75 */  {"LD (IY%s), L", DISP, false},
  /* 0x76 */  {"HALT", NONE, true},
  /* 0x77 */  {"LD (IY%s), A", DISP, false},
  /* 0x78 */  {"LD A,B", NONE, true},
  /* 0x79 */  {"LD A,C", NONE, true},
  /* 0x7a */  {"LD A,D", NONE, true},
  /* 0x7b */  {"LD A,E", NONE, true},
  /* 0x7c */  {"LD A,IYH", NONE, true},
  /* 0x7d */  {"LD A,IYL", NONE, true},
  /* 0x7e */  {"LD A, (IY%s)", DISP, false},
  /* 0x7f */  {"LD A,A", NONE, true},
  /* 0x80 */  {"ADD B", NONE, true},
  /* 0x81 */  {"ADD C", NONE, true},
  /* 0x82 */  {"ADD D", NONE, true},
  /* 0x83 */  {"ADD E", NONE, true},
  /* 0x84 */  {"ADD IYH", NONE, true},
  /* 0x85 */  {"ADD IYL", NONE, true},
  /* 0x86 */  {"ADD (IY%s)", DISP, false},
  /* 0x87 */  {"ADD A", NONE, true},
  /* 0x88 */  {"ADC B", NONE, true},
  /* 0x89 */  {"ADC C", NONE, true},
  /* 0x8a */  {"ADC D", NONE, true},
  /* 0x8b */  {"ADC E", NONE, true},
  /* 0x8c */  {"ADC IYH", NONE, true},
  /* 0x8d */  {"ADC IYL", NONE, true},
  /* 0x8e */  {"ADC (IY%s)", DISP, false},
  /* 0x8f */  {"ADC A", NONE, true},
  /* 0x90 */  {"SUB B", NONE, true},
  /* 0x91 */  {"SUB C", NONE, true},
  /* 0x92 */  {"SUB D", NONE, true},
  /* 0x93 */  {"SUB E", NONE, true},
  /* 0x94 */  {"SUB IYH", NONE, true},
  /* 0x95 */  {"SUB IYL", NONE, true},
  /* 0x96 */  {"SUB (IY%s)", DISP, false},
  /* 0x97 */  {"SUB A", NONE, true},
  /* 0x98 */  {"SBC B", NONE, true},
  /* 0x99 */  {"SBC C", NONE, true},
  /* 0x9a */  {"SBC D", NONE, true},
  /* 0x9b */  {"SBC E", NONE, true},
  /* 0x9c */  {"SBC IYH", NONE, true},
  /* 0x9d */  {"SBC IYL", NONE, true},
  /* 0x9e */  {"SBC (IY%s)", DISP, false},
  /* 0x9f */  {"SBC A", NONE, true},
  /* 0xa0 */  {"AND B", NONE, true},
  /* 0xa1 */  {"AND C", NONE, true},
  /* 0xa2 */  {"AND D", NONE, true},
  /* 0xa3 */  {"AND E", NONE, true},
  /* 0xa4 */  {"AND IYH", NONE, true},
  /* 0xa5 */  {"AND IYL", NONE, true},
  /* 0xa6 */  {"AND (IY%s)", DISP, false},
  /* 0xa7 */  {"AND A", NONE, true},
  /* 0xa8 */  {"XOR B", NONE, true},
  /* 0xa9 */  {"XOR C", NONE, true},
  /* 0xaa */  {"XOR D", NONE, true},
  /* 0xab */  {"XOR E", NONE, true},
  /* 0xac */  {"XOR IYH", NONE, true},
  /* 0xad */  {"XOR IYL", NONE, true},
  /* 0xae */  {"XOR (IY%s)", DISP, false},
  /* 0xaf */  {"XOR A", NONE, true},
  /* 0xb0 */  {"OR B", NONE, true},
  /* 0xb1 */  {"OR C", NONE, true},
  /* 0xb2 */  {"OR D", NONE, true},
  /* 0xb3 */  {"OR E", NONE, true},
  /* 0xb4 */  {"OR IYH", NONE, true},
  /* 0xb5 */  {"OR IYL", NONE, true},
  /* 0xb6 */  {"OR (IY%s)", DISP, false},
  /* 0xb7 */  {"OR A", NONE, true},
  /* 0xb8 */  {"CP B", NONE, true},
  /* 0xb9 */  {"CP C", NONE, true},
  /* 0xba */  {"CP D", NONE, true},
  /* 0xbb */  {"CP E", NONE, true},
  /* 0xbc */  {"CP IYH", NONE, true},
  /* 0xbd */  {"CP IYL", NONE, true},
  /* 0xbe */  {"CP (IY%s)", DISP, false},
  /* 0xbf */  {"CP A", NONE, true},
  /* 0xc0 */  {"RET NZ", NONE, true},
  /* 0xc1 */  {"POP BC", NONE, true},
  /* 0xc2 */  {"JP NZ, %s", ABS16, true},
  /* 0xc3 */  {"JP %s", ABS16, true},
  /* 0xc4 */  {"CALL NZ, %s", ABS16, true},
  /* 0xc5 */  {"PUSH BC", NONE, true},
  /* 0xc6 */  {"ADD #%s", ABS8, true},
  /* 0xc7 */  {"RST 00", NONE, true},
  /* 0xc8 */  {"RET Z", NONE, true},
  /* 0xc9 */  {"RET", NONE, true},
  /* 0xca */  {"JP Z, %s", ABS16, true},
  /* 0xcb */  {"???", NONE, true},
  /* 0xcc */  {"CALL Z, %s", ABS16, true},
  /* 0xcd */  {"CALL %s", ABS16, true},
  /* 0xce */  {"ADC #%s", ABS8, true},
  /* 0xcf */  {"RST 08", NONE, true},
  /* 0xd0 */  {"RET NC", NONE, true},
  /* 0xd1 */  {"POP DE", NONE, true},
  /* 0xd2 */  {"JP NC, %s", ABS16, true},
  /* 0xd3 */  {"OUTA %s", ABS8, true},
  /* 0xd4 */  {"CALL NC, %s", ABS16, true},
  /* 0xd5 */  {"PUSH DE", NONE, true},
  /* 0xd6 */  {"SUB #%s", ABS8, true},
  /* 0xd7 */  {"RST 10", NONE, true},
  /* 0xd8 */  {"RET C", NONE, true},
  /* 0xd9 */  {"EXX", NONE, true},
  /* 0xda */  {"JP C, %s", ABS16, true},
  /* 0xdb */  {"INA %s", ABS8, true},
  /* 0xdc */  {"CALL C, %s", ABS16, true},
  /* 0xdd */  {"NOP #%s", ABS8, true},
  /* 0xde */  {"SBC #%s", ABS8, true},
  /* 0xdf */  {"RST 18", NONE, true},
  /* 0xe0 */  {"RET PO", NONE, true},
  /* 0xe1 */  {"POP IY", NONE, false},
  /* 0xe2 */  {"JP PO, %s", ABS16, true},
  /* 0xe3 */  {"EX (SP),IY", NONE, false},
  /* 0xe4 */  {"CALL PO, %s", ABS16, true},
  /* 0xe5 */  {"PUSH IY", NONE, false},
  /* 0xe6 */  {"AND #%s", ABS8, true},
  /* 0xe7 */  {"RST 20", NONE, true},
  /* 0xe8 */  {"RET PE", NONE, true},
  /* 0xe9 */  {"JP (IY)", NONE, false},
  /* 0xea */  {"JP PE, %s", ABS16, true},
  /* 0xeb */  {"EX DE,HL", NONE, true},
  /* 0xec */  {"CALL PE, %s", ABS16, true},
  /* 0xed */  {"PFX_FDED #%s", ABS8, true},
  /* 0xee */  {"XOR #%s", ABS8, true},
  /* 0xef */  {"RST 28", NONE, true},
  /* 0xf0 */  {"RET P", NONE, true},
  /* 0xf1 */  {"POP AF", NONE, true},
  /* 0xf2 */  {"JP P, %s", ABS16, true},
  /* 0xf3 */  {"DI", NONE, true},
  /* 0xf4 */  {"CALL P, %s", ABS16, true},
  /* 0xf5 */  {"PUSH AF", NONE, true},
  /* 0xf6 */  {"OR #%s", ABS8, true},
  /* 0xf7 */  {"RST 30", NONE, true},
  /* 0xf8 */  {"RET M", NONE, true},
  /* 0xf9 */  {"LD SP,IY", NONE, false},
  /* 0xfa */  {"JP M, %s", ABS16, true},
  /* 0xfb */  {"EI", NONE, true},
  /* 0xfc */  {"CALL M, %s", ABS16, true},
  /* 0xfd */  {"NOP #%s", ABS8, true},
  /* 0xfe */  {"CP #%s", ABS8, true},
  /* 0xff */  {"RST 38", NONE, true},
};

InstrDesc opcodes_ddcb[256] = {
    /* 0x00 */  {"RLC (IX%s), B", DISP, true},
    /* 0x01 */  {"RLC (IX%s), C", DISP, true},
    /* 0x02 */  {"RLC (IX%s), D", DISP, true},
    /* 0x03 */  {"RLC (IX%s), E", DISP, true},
    /* 0x04 */  {"RLC (IX%s), H", DISP, true},
    /* 0x05 */  {"RLC (IX%s), L", DISP, true},
    /* 0x06 */  {"RLC (IX%s)", DISP, false},
    /* 0x07 */  {"RLC (IX%s), A", DISP, true},
    /* 0x08 */  {"RRC (IX%s), B", DISP, true},
    /* 0x09 */  {"RRC (IX%s), C", DISP, true},
    /* 0x0a */  {"RRC (IX%s), D", DISP, true},
    /* 0x0b */  {"RRC (IX%s), E", DISP, true},
    /* 0x0c */  {"RRC (IX%s), H", DISP, true},
    /* 0x0d */  {"RRC (IX%s), L", DISP, true},
    /* 0x0e */  {"RRC (IX%s)", DISP, false},
    /* 0x0f */  {"RRC (IX%s), A", DISP, true},
    /* 0x10 */  {"RL (IX%s), B", DISP, true},
    /* 0x11 */  {"RL (IX%s), C", DISP, true},
    /* 0x12 */  {"RL (IX%s), D", DISP, true},
    /* 0x13 */  {"RL (IX%s), E", DISP, true},
    /* 0x14 */  {"RL (IX%s), H", DISP, true},
    /* 0x15 */  {"RL (IX%s), L", DISP, true},
    /* 0x16 */  {"RL (IX%s)", DISP, false},
    /* 0x17 */  {"RL (IX%s), A", DISP, true},
    /* 0x18 */  {"RR (IX%s), B", DISP, true},
    /* 0x19 */  {"RR (IX%s), C", DISP, true},
    /* 0x1a */  {"RR (IX%s), D", DISP, true},
    /* 0x1b */  {"RR (IX%s), E", DISP, true},
    /* 0x1c */  {"RR (IX%s), H", DISP, true},
    /* 0x1d */  {"RR (IX%s), L", DISP, true},
    /* 0x1e */  {"RR (IX%s)", DISP, false},
    /* 0x1f */  {"RR (IX%s), A", DISP, true},
    /* 0x20 */  {"SLA (IX%s), B", DISP, true},
    /* 0x21 */  {"SLA (IX%s), C", DISP, true},
    /* 0x22 */  {"SLA (IX%s), D", DISP, true},
    /* 0x23 */  {"SLA (IX%s), E", DISP, true},
    /* 0x24 */  {"SLA (IX%s), H", DISP, true},
    /* 0x25 */  {"SLA (IX%s), L", DISP, true},
    /* 0x26 */  {"SLA (IX%s)", DISP, false},
    /* 0x27 */  {"SLA (IX%s), A", DISP, true},
    /* 0x28 */  {"SRA (IX%s), B", DISP, true},
    /* 0x29 */  {"SRA (IX%s), C", DISP, true},
    /* 0x2a */  {"SRA (IX%s), D", DISP, true},
    /* 0x2b */  {"SRA (IX%s), E", DISP, true},
    /* 0x2c */  {"SRA (IX%s), H", DISP, true},
    /* 0x2d */  {"SRA (IX%s), L", DISP, true},
    /* 0x2e */  {"SRA (IX%s)", DISP, false},
    /* 0x2f */  {"SRA (IX%s), A", DISP, true},
    /* 0x30 */  {"SLL (IX%s), B", DISP, true},
    /* 0x31 */  {"SLL (IX%s), C", DISP, true},
    /* 0x32 */  {"SLL (IX%s), D", DISP, true},
    /* 0x33 */  {"SLL (IX%s), E", DISP, true},
    /* 0x34 */  {"SLL (IX%s), H", DISP, true},
    /* 0x35 */  {"SLL (IX%s), L", DISP, true},
    /* 0x36 */  {"SLL (IX%s)", DISP, true},
    /* 0x37 */  {"SLL (IX%s), A", DISP, true},
    /* 0x38 */  {"SRL (IX%s), B", DISP, true},
    /* 0x39 */  {"SRL (IX%s), C", DISP, true},
    /* 0x3a */  {"SRL (IX%s), D", DISP, true},
    /* 0x3b */  {"SRL (IX%s), E", DISP, true},
    /* 0x3c */  {"SRL (IX%s), H", DISP, true},
    /* 0x3d */  {"SRL (IX%s), L", DISP, true},
    /* 0x3e */  {"SRL (IX%s)", DISP, false},
    /* 0x3f */  {"SRL (IX%s), A", DISP, true},
    /* 0x40 */  {"BIT 0, (IX%s)", DISP, true},
    /* 0x41 */  {"BIT 0, (IX%s)", DISP, true},
    /* 0x42 */  {"BIT 0, (IX%s)", DISP, true},
    /* 0x43 */  {"BIT 0, (IX%s)", DISP, true},
    /* 0x44 */  {"BIT 0, (IX%s)", DISP, true},
    /* 0x45 */  {"BIT 0, (IX%s)", DISP, true},
    /* 0x46 */  {"BIT 0, (IX%s)", DISP, false},
    /* 0x47 */  {"BIT 0, (IX%s)", DISP, true},
    /* 0x48 */  {"BIT 1, (IX%s)", DISP, true},
    /* 0x49 */  {"BIT 1, (IX%s)", DISP, true},
    /* 0x4a */  {"BIT 1, (IX%s)", DISP, true},
    /* 0x4b */  {"BIT 1, (IX%s)", DISP, true},
    /* 0x4c */  {"BIT 1, (IX%s)", DISP, true},
    /* 0x4d */  {"BIT 1, (IX%s)", DISP, true},
    /* 0x4e */  {"BIT 1, (IX%s)", DISP, false},
    /* 0x4f */  {"BIT 1, (IX%s)", DISP, true},
    /* 0x50 */  {"BIT 2, (IX%s)", DISP, true},
    /* 0x51 */  {"BIT 2, (IX%s)", DISP, true},
    /* 0x52 */  {"BIT 2, (IX%s)", DISP, true},
    /* 0x53 */  {"BIT 2, (IX%s)", DISP, true},
    /* 0x54 */  {"BIT 2, (IX%s)", DISP, true},
    /* 0x55 */  {"BIT 2, (IX%s)", DISP, true},
    /* 0x56 */  {"BIT 2, (IX%s)", DISP, false},
    /* 0x57 */  {"BIT 2, (IX%s)", DISP, true},
    /* 0x58 */  {"BIT 3, (IX%s)", DISP, true},
    /* 0x59 */  {"BIT 3, (IX%s)", DISP, true},
    /* 0x5a */  {"BIT 3, (IX%s)", DISP, true},
    /* 0x5b */  {"BIT 3, (IX%s)", DISP, true},
    /* 0x5c */  {"BIT 3, (IX%s)", DISP, true},
    /* 0x5d */  {"BIT 3, (IX%s)", DISP, true},
    /* 0x5e */  {"BIT 3, (IX%s)", DISP, false},
    /* 0x5f */  {"BIT 3, (IX%s)", DISP, true},
    /* 0x60 */  {"BIT 4, (IX%s)", DISP, true},
    /* 0x61 */  {"BIT 4, (IX%s)", DISP, true},
    /* 0x62 */  {"BIT 4, (IX%s)", DISP, true},
    /* 0x63 */  {"BIT 4, (IX%s)", DISP, true},
    /* 0x64 */  {"BIT 4, (IX%s)", DISP, true},
    /* 0x65 */  {"BIT 4, (IX%s)", DISP, true},
    /* 0x66 */  {"BIT 4, (IX%s)", DISP, false},
    /* 0x67 */  {"BIT 4, (IX%s)", DISP, true},
    /* 0x68 */  {"BIT 5, (IX%s)", DISP, true},
    /* 0x69 */  {"BIT 5, (IX%s)", DISP, true},
    /* 0x6a */  {"BIT 5, (IX%s)", DISP, true},
    /* 0x6b */  {"BIT 5, (IX%s)", DISP, true},
    /* 0x6c */  {"BIT 5, (IX%s)", DISP, true},
    /* 0x6d */  {"BIT 5, (IX%s)", DISP, true},
    /* 0x6e */  {"BIT 5, (IX%s)", DISP, false},
    /* 0x6f */  {"BIT 5, (IX%s)", DISP, true},
    /* 0x70 */  {"BIT 6, (IX%s)", DISP, true},
    /* 0x71 */  {"BIT 6, (IX%s)", DISP, true},
    /* 0x72 */  {"BIT 6, (IX%s)", DISP, true},
    /* 0x73 */  {"BIT 6, (IX%s)", DISP, true},
    /* 0x74 */  {"BIT 6, (IX%s)", DISP, true},
    /* 0x75 */  {"BIT 6, (IX%s)", DISP, true},
    /* 0x76 */  {"BIT 6, (IX%s)", DISP, false},
    /* 0x77 */  {"BIT 6, (IX%s)", DISP, true},
    /* 0x78 */  {"BIT 7, (IX%s)", DISP, true},
    /* 0x79 */  {"BIT 7, (IX%s)", DISP, true},
    /* 0x7a */  {"BIT 7, (IX%s)", DISP, true},
    /* 0x7b */  {"BIT 7, (IX%s)", DISP, true},
    /* 0x7c */  {"BIT 7, (IX%s)", DISP, true},
    /* 0x7d */  {"BIT 7, (IX%s)", DISP, true},
    /* 0x7e */  {"BIT 7, (IX%s)", DISP, false},
    /* 0x7f */  {"BIT 7, (IX%s)", DISP, true},
    /* 0x80 */  {"RES 0, (IX%s), B", DISP, true},
    /* 0x81 */  {"RES 0, (IX%s), C", DISP, true},
    /* 0x82 */  {"RES 0, (IX%s), D", DISP, true},
    /* 0x83 */  {"RES 0, (IX%s), E", DISP, true},
    /* 0x84 */  {"RES 0, (IX%s), H", DISP, true},
    /* 0x85 */  {"RES 0, (IX%s), L", DISP, true},
    /* 0x86 */  {"RES 0, (IX%s)", DISP, false},
    /* 0x87 */  {"RES 0, (IX%s), A", DISP, true},
    /* 0x88 */  {"RES 1, (IX%s), B", DISP, true},
    /* 0x89 */  {"RES 1, (IX%s), C", DISP, true},
    /* 0x8a */  {"RES 1, (IX%s), D", DISP, true},
    /* 0x8b */  {"RES 1, (IX%s), E", DISP, true},
    /* 0x8c */  {"RES 1, (IX%s), H", DISP, true},
    /* 0x8d */  {"RES 1, (IX%s), L", DISP, true},
    /* 0x8e */  {"RES 1, (IX%s)", DISP, false},
    /* 0x8f */  {"RES 1, (IX%s), A", DISP, true},
    /* 0x90 */  {"RES 2, (IX%s), B", DISP, true},
    /* 0x91 */  {"RES 2, (IX%s), C", DISP, true},
    /* 0x92 */  {"RES 2, (IX%s), D", DISP, true},
    /* 0x93 */  {"RES 2, (IX%s), E", DISP, true},
    /* 0x94 */  {"RES 2, (IX%s), H", DISP, true},
    /* 0x95 */  {"RES 2, (IX%s), L", DISP, true},
    /* 0x96 */  {"RES 2, (IX%s)", DISP, false},
    /* 0x97 */  {"RES 2, (IX%s), A", DISP, true},
    /* 0x98 */  {"RES 3, (IX%s), B", DISP, true},
    /* 0x99 */  {"RES 3, (IX%s), C", DISP, true},
    /* 0x9a */  {"RES 3, (IX%s), D", DISP, true},
    /* 0x9b */  {"RES 3, (IX%s), E", DISP, true},
    /* 0x9c */  {"RES 3, (IX%s), H", DISP, true},
    /* 0x9d */  {"RES 3, (IX%s), L", DISP, true},
    /* 0x9e */  {"RES 3, (IX%s)", DISP, false},
    /* 0x9f */  {"RES 3, (IX%s), A", DISP, true},
    /* 0xa0 */  {"RES 4, (IX%s), B", DISP, true},
    /* 0xa1 */  {"RES 4, (IX%s), C", DISP, true},
    /* 0xa2 */  {"RES 4, (IX%s), D", DISP, true},
    /* 0xa3 */  {"RES 4, (IX%s), E", DISP, true},
    /* 0xa4 */  {"RES 4, (IX%s), H", DISP, true},
    /* 0xa5 */  {"RES 4, (IX%s), L", DISP, true},
    /* 0xa6 */  {"RES 4, (IX%s)", DISP, false},
    /* 0xa7 */  {"RES 4, (IX%s), A", DISP, true},
    /* 0xa8 */  {"RES 5, (IX%s), B", DISP, true},
    /* 0xa9 */  {"RES 5, (IX%s), C", DISP, true},
    /* 0xaa */  {"RES 5, (IX%s), D", DISP, true},
    /* 0xab */  {"RES 5, (IX%s), E", DISP, true},
    /* 0xac */  {"RES 5, (IX%s), H", DISP, true},
    /* 0xad */  {"RES 5, (IX%s), L", DISP, true},
    /* 0xae */  {"RES 5, (IX%s)", DISP, false},
    /* 0xaf */  {"RES 5, (IX%s), A", DISP, true},
    /* 0xb0 */  {"RES 6, (IX%s), B", DISP, true},
    /* 0xb1 */  {"RES 6, (IX%s), C", DISP, true},
    /* 0xb2 */  {"RES 6, (IX%s), D", DISP, true},
    /* 0xb3 */  {"RES 6, (IX%s), E", DISP, true},
    /* 0xb4 */  {"RES 6, (IX%s), H", DISP, true},
    /* 0xb5 */  {"RES 6, (IX%s), L", DISP, true},
    /* 0xb6 */  {"RES 6, (IX%s)", DISP, false},
    /* 0xb7 */  {"RES 6, (IX%s), A", DISP, true},
    /* 0xb8 */  {"RES 7, (IX%s), B", DISP, true},
    /* 0xb9 */  {"RES 7, (IX%s), C", DISP, true},
    /* 0xba */  {"RES 7, (IX%s), D", DISP, true},
    /* 0xbb */  {"RES 7, (IX%s), E", DISP, true},
    /* 0xbc */  {"RES 7, (IX%s), H", DISP, true},
    /* 0xbd */  {"RES 7, (IX%s), L", DISP, true},
    /* 0xbe */  {"RES 7, (IX%s)", DISP, false},
    /* 0xbf */  {"RES 7, (IX%s), A", DISP, true},
    /* 0xc0 */  {"SET 0, (IX%s), B", DISP, true},
    /* 0xc1 */  {"SET 0, (IX%s), C", DISP, true},
    /* 0xc2 */  {"SET 0, (IX%s), D", DISP, true},
    /* 0xc3 */  {"SET 0, (IX%s), E", DISP, true},
    /* 0xc4 */  {"SET 0, (IX%s), H", DISP, true},
    /* 0xc5 */  {"SET 0, (IX%s), L", DISP, true},
    /* 0xc6 */  {"SET 0, (IX%s)", DISP, false},
    /* 0xc7 */  {"SET 0, (IX%s), A", DISP, true},
    /* 0xc8 */  {"SET 1, (IX%s), B", DISP, true},
    /* 0xc9 */  {"SET 1, (IX%s), C", DISP, true},
    /* 0xca */  {"SET 1, (IX%s), D", DISP, true},
    /* 0xcb */  {"SET 1, (IX%s), E", DISP, true},
    /* 0xcc */  {"SET 1, (IX%s), H", DISP, true},
    /* 0xcd */  {"SET 1, (IX%s), L", DISP, true},
    /* 0xce */  {"SET 1, (IX%s)", DISP, false},
    /* 0xcf */  {"SET 1, (IX%s), A", DISP, true},
    /* 0xd0 */  {"SET 2, (IX%s), B", DISP, true},
    /* 0xd1 */  {"SET 2, (IX%s), C", DISP, true},
    /* 0xd2 */  {"SET 2, (IX%s), D", DISP, true},
    /* 0xd3 */  {"SET 2, (IX%s), E", DISP, true},
    /* 0xd4 */  {"SET 2, (IX%s), H", DISP, true},
    /* 0xd5 */  {"SET 2, (IX%s), L", DISP, true},
    /* 0xd6 */  {"SET 2, (IX%s)", DISP, false},
    /* 0xd7 */  {"SET 2, (IX%s), A", DISP, true},
    /* 0xd8 */  {"SET 3, (IX%s), B", DISP, true},
    /* 0xd9 */  {"SET 3, (IX%s), C", DISP, true},
    /* 0xda */  {"SET 3, (IX%s), D", DISP, true},
    /* 0xdb */  {"SET 3, (IX%s), E", DISP, true},
    /* 0xdc */  {"SET 3, (IX%s), H", DISP, true},
    /* 0xdd */  {"SET 3, (IX%s), L", DISP, true},
    /* 0xde */  {"SET 3, (IX%s)", DISP, false},
    /* 0xdf */  {"SET 3, (IX%s), A", DISP, true},
    /* 0xe0 */  {"SET 4, (IX%s), B", DISP, true},
    /* 0xe1 */  {"SET 4, (IX%s), C", DISP, true},
    /* 0xe2 */  {"SET 4, (IX%s), D", DISP, true},
    /* 0xe3 */  {"SET 4, (IX%s), E", DISP, true},
    /* 0xe4 */  {"SET 4, (IX%s), H", DISP, true},
    /* 0xe5 */  {"SET 4, (IX%s), L", DISP, true},
    /* 0xe6 */  {"SET 4, (IX%s)", DISP, false},
    /* 0xe7 */  {"SET 4, (IX%s), A", DISP, true},
    /* 0xe8 */  {"SET 5, (IX%s), B", DISP, true},
    /* 0xe9 */  {"SET 5, (IX%s), C", DISP, true},
    /* 0xea */  {"SET 5, (IX%s), D", DISP, true},
    /* 0xeb */  {"SET 5, (IX%s), E", DISP, true},
    /* 0xec */  {"SET 5, (IX%s), H", DISP, true},
    /* 0xed */  {"SET 5, (IX%s), L", DISP, true},
    /* 0xee */  {"SET 5, (IX%s)", DISP, false},
    /* 0xef */  {"SET 5, (IX%s), A", DISP, true},
    /* 0xf0 */  {"SET 6, (IX%s), B", DISP, true},
    /* 0xf1 */  {"SET 6, (IX%s), C", DISP, true},
    /* 0xf2 */  {"SET 6, (IX%s), D", DISP, true},
    /* 0xf3 */  {"SET 6, (IX%s), E", DISP, true},
    /* 0xf4 */  {"SET 6, (IX%s), H", DISP, true},
    /* 0xf5 */  {"SET 6, (IX%s), L", DISP, true},
    /* 0xf6 */  {"SET 6, (IX%s)", DISP, false},
    /* 0xf7 */  {"SET 6, (IX%s), A", DISP, true},
    /* 0xf8 */  {"SET 7, (IX%s), B", DISP, true},
    /* 0xf9 */  {"SET 7, (IX%s), C", DISP, true},
    /* 0xfa */  {"SET 7, (IX%s), D", DISP, true},
    /* 0xfb */  {"SET 7, (IX%s), E", DISP, true},
    /* 0xfc */  {"SET 7, (IX%s), H", DISP, true},
    /* 0xfd */  {"SET 7, (IX%s), L", DISP, true},
    /* 0xfe */  {"SET 7, (IX%s)", DISP, false},
    /* 0xff */  {"SET 7, (IX%s), A", DISP, true},
};

InstrDesc opcodes_fdcb[256] = {
    /* 0x00 */  {"RLC (IY%s), B", DISP, true},
    /* 0x01 */  {"RLC (IY%s), C", DISP, true},
    /* 0x02 */  {"RLC (IY%s), D", DISP, true},
    /* 0x03 */  {"RLC (IY%s), E", DISP, true},
    /* 0x04 */  {"RLC (IY%s), H", DISP, true},
    /* 0x05 */  {"RLC (IY%s), L", DISP, true},
    /* 0x06 */  {"RLC (IY%s)", DISP, false},
    /* 0x07 */  {"RLC (IY%s), A", DISP, true},
    /* 0x08 */  {"RRC (IY%s), B", DISP, true},
    /* 0x09 */  {"RRC (IY%s), C", DISP, true},
    /* 0x0a */  {"RRC (IY%s), D", DISP, true},
    /* 0x0b */  {"RRC (IY%s), E", DISP, true},
    /* 0x0c */  {"RRC (IY%s), H", DISP, true},
    /* 0x0d */  {"RRC (IY%s), L", DISP, true},
    /* 0x0e */  {"RRC (IY%s)", DISP, false},
    /* 0x0f */  {"RRC (IY%s), A", DISP, true},
    /* 0x10 */  {"RL (IY%s), B", DISP, true},
    /* 0x11 */  {"RL (IY%s), C", DISP, true},
    /* 0x12 */  {"RL (IY%s), D", DISP, true},
    /* 0x13 */  {"RL (IY%s), E", DISP, true},
    /* 0x14 */  {"RL (IY%s), H", DISP, true},
    /* 0x15 */  {"RL (IY%s), L", DISP, true},
    /* 0x16 */  {"RL (IY%s)", DISP, false},
    /* 0x17 */  {"RL (IY%s), A", DISP, true},
    /* 0x18 */  {"RR (IY%s), B", DISP, true},
    /* 0x19 */  {"RR (IY%s), C", DISP, true},
    /* 0x1a */  {"RR (IY%s), D", DISP, true},
    /* 0x1b */  {"RR (IY%s), E", DISP, true},
    /* 0x1c */  {"RR (IY%s), H", DISP, true},
    /* 0x1d */  {"RR (IY%s), L", DISP, true},
    /* 0x1e */  {"RR (IY%s)", DISP, false},
    /* 0x1f */  {"RR (IY%s), A", DISP, true},
    /* 0x20 */  {"SLA (IY%s), B", DISP, true},
    /* 0x21 */  {"SLA (IY%s), C", DISP, true},
    /* 0x22 */  {"SLA (IY%s), D", DISP, true},
    /* 0x23 */  {"SLA (IY%s), E", DISP, true},
    /* 0x24 */  {"SLA (IY%s), H", DISP, true},
    /* 0x25 */  {"SLA (IY%s), L", DISP, true},
    /* 0x26 */  {"SLA (IY%s)", DISP, false},
    /* 0x27 */  {"SLA (IY%s), A", DISP, true},
    /* 0x28 */  {"SRA (IY%s), B", DISP, true},
    /* 0x29 */  {"SRA (IY%s), C", DISP, true},
    /* 0x2a */  {"SRA (IY%s), D", DISP, true},
    /* 0x2b */  {"SRA (IY%s), E", DISP, true},
    /* 0x2c */  {"SRA (IY%s), H", DISP, true},
    /* 0x2d */  {"SRA (IY%s), L", DISP, true},
    /* 0x2e */  {"SRA (IY%s)", DISP, false},
    /* 0x2f */  {"SRA (IY%s), A", DISP, true},
    /* 0x30 */  {"SLL (IY%s), B", DISP, true},
    /* 0x31 */  {"SLL (IY%s), C", DISP, true},
    /* 0x32 */  {"SLL (IY%s), D", DISP, true},
    /* 0x33 */  {"SLL (IY%s), E", DISP, true},
    /* 0x34 */  {"SLL (IY%s), H", DISP, true},
    /* 0x35 */  {"SLL (IY%s), L", DISP, true},
    /* 0x36 */  {"SLL (IY%s)", DISP, true},
    /* 0x37 */  {"SLL (IY%s), A", DISP, true},
    /* 0x38 */  {"SRL (IY%s), B", DISP, true},
    /* 0x39 */  {"SRL (IY%s), C", DISP, true},
    /* 0x3a */  {"SRL (IY%s), D", DISP, true},
    /* 0x3b */  {"SRL (IY%s), E", DISP, true},
    /* 0x3c */  {"SRL (IY%s), H", DISP, true},
    /* 0x3d */  {"SRL (IY%s), L", DISP, true},
    /* 0x3e */  {"SRL (IY%s)", DISP, false},
    /* 0x3f */  {"SRL (IY%s), A", DISP, true},
    /* 0x40 */  {"BIT 0, (IY%s)", DISP, true},
    /* 0x41 */  {"BIT 0, (IY%s)", DISP, true},
    /* 0x42 */  {"BIT 0, (IY%s)", DISP, true},
    /* 0x43 */  {"BIT 0, (IY%s)", DISP, true},
    /* 0x44 */  {"BIT 0, (IY%s)", DISP, true},
    /* 0x45 */  {"BIT 0, (IY%s)", DISP, true},
    /* 0x46 */  {"BIT 0, (IY%s)", DISP, false},
    /* 0x47 */  {"BIT 0, (IY%s)", DISP, true},
    /* 0x48 */  {"BIT 1, (IY%s)", DISP, true},
    /* 0x49 */  {"BIT 1, (IY%s)", DISP, true},
    /* 0x4a */  {"BIT 1, (IY%s)", DISP, true},
    /* 0x4b */  {"BIT 1, (IY%s)", DISP, true},
    /* 0x4c */  {"BIT 1, (IY%s)", DISP, true},
    /* 0x4d */  {"BIT 1, (IY%s)", DISP, true},
    /* 0x4e */  {"BIT 1, (IY%s)", DISP, false},
    /* 0x4f */  {"BIT 1, (IY%s)", DISP, true},
    /* 0x50 */  {"BIT 2, (IY%s)", DISP, true},
    /* 0x51 */  {"BIT 2, (IY%s)", DISP, true},
    /* 0x52 */  {"BIT 2, (IY%s)", DISP, true},
    /* 0x53 */  {"BIT 2, (IY%s)", DISP, true},
    /* 0x54 */  {"BIT 2, (IY%s)", DISP, true},
    /* 0x55 */  {"BIT 2, (IY%s)", DISP, true},
    /* 0x56 */  {"BIT 2, (IY%s)", DISP, false},
    /* 0x57 */  {"BIT 2, (IY%s)", DISP, true},
    /* 0x58 */  {"BIT 3, (IY%s)", DISP, true},
    /* 0x59 */  {"BIT 3, (IY%s)", DISP, true},
    /* 0x5a */  {"BIT 3, (IY%s)", DISP, true},
    /* 0x5b */  {"BIT 3, (IY%s)", DISP, true},
    /* 0x5c */  {"BIT 3, (IY%s)", DISP, true},
    /* 0x5d */  {"BIT 3, (IY%s)", DISP, true},
    /* 0x5e */  {"BIT 3, (IY%s)", DISP, false},
    /* 0x5f */  {"BIT 3, (IY%s)", DISP, true},
    /* 0x60 */  {"BIT 4, (IY%s)", DISP, true},
    /* 0x61 */  {"BIT 4, (IY%s)", DISP, true},
    /* 0x62 */  {"BIT 4, (IY%s)", DISP, true},
    /* 0x63 */  {"BIT 4, (IY%s)", DISP, true},
    /* 0x64 */  {"BIT 4, (IY%s)", DISP, true},
    /* 0x65 */  {"BIT 4, (IY%s)", DISP, true},
    /* 0x66 */  {"BIT 4, (IY%s)", DISP, false},
    /* 0x67 */  {"BIT 4, (IY%s)", DISP, true},
    /* 0x68 */  {"BIT 5, (IY%s)", DISP, true},
    /* 0x69 */  {"BIT 5, (IY%s)", DISP, true},
    /* 0x6a */  {"BIT 5, (IY%s)", DISP, true},
    /* 0x6b */  {"BIT 5, (IY%s)", DISP, true},
    /* 0x6c */  {"BIT 5, (IY%s)", DISP, true},
    /* 0x6d */  {"BIT 5, (IY%s)", DISP, true},
    /* 0x6e */  {"BIT 5, (IY%s)", DISP, false},
    /* 0x6f */  {"BIT 5, (IY%s)", DISP, true},
    /* 0x70 */  {"BIT 6, (IY%s)", DISP, true},
    /* 0x71 */  {"BIT 6, (IY%s)", DISP, true},
    /* 0x72 */  {"BIT 6, (IY%s)", DISP, true},
    /* 0x73 */  {"BIT 6, (IY%s)", DISP, true},
    /* 0x74 */  {"BIT 6, (IY%s)", DISP, true},
    /* 0x75 */  {"BIT 6, (IY%s)", DISP, true},
    /* 0x76 */  {"BIT 6, (IY%s)", DISP, false},
    /* 0x77 */  {"BIT 6, (IY%s)", DISP, true},
    /* 0x78 */  {"BIT 7, (IY%s)", DISP, true},
    /* 0x79 */  {"BIT 7, (IY%s)", DISP, true},
    /* 0x7a */  {"BIT 7, (IY%s)", DISP, true},
    /* 0x7b */  {"BIT 7, (IY%s)", DISP, true},
    /* 0x7c */  {"BIT 7, (IY%s)", DISP, true},
    /* 0x7d */  {"BIT 7, (IY%s)", DISP, true},
    /* 0x7e */  {"BIT 7, (IY%s)", DISP, false},
    /* 0x7f */  {"BIT 7, (IY%s)", DISP, true},
    /* 0x80 */  {"RES 0, (IY%s), B", DISP, true},
    /* 0x81 */  {"RES 0, (IY%s), C", DISP, true},
    /* 0x82 */  {"RES 0, (IY%s), D", DISP, true},
    /* 0x83 */  {"RES 0, (IY%s), E", DISP, true},
    /* 0x84 */  {"RES 0, (IY%s), H", DISP, true},
    /* 0x85 */  {"RES 0, (IY%s), L", DISP, true},
    /* 0x86 */  {"RES 0, (IY%s)", DISP, false},
    /* 0x87 */  {"RES 0, (IY%s), A", DISP, true},
    /* 0x88 */  {"RES 1, (IY%s), B", DISP, true},
    /* 0x89 */  {"RES 1, (IY%s), C", DISP, true},
    /* 0x8a */  {"RES 1, (IY%s), D", DISP, true},
    /* 0x8b */  {"RES 1, (IY%s), E", DISP, true},
    /* 0x8c */  {"RES 1, (IY%s), H", DISP, true},
    /* 0x8d */  {"RES 1, (IY%s), L", DISP, true},
    /* 0x8e */  {"RES 1, (IY%s)", DISP, false},
    /* 0x8f */  {"RES 1, (IY%s), A", DISP, true},
    /* 0x90 */  {"RES 2, (IY%s), B", DISP, true},
    /* 0x91 */  {"RES 2, (IY%s), C", DISP, true},
    /* 0x92 */  {"RES 2, (IY%s), D", DISP, true},
    /* 0x93 */  {"RES 2, (IY%s), E", DISP, true},
    /* 0x94 */  {"RES 2, (IY%s), H", DISP, true},
    /* 0x95 */  {"RES 2, (IY%s), L", DISP, true},
    /* 0x96 */  {"RES 2, (IY%s)", DISP, false},
    /* 0x97 */  {"RES 2, (IY%s), A", DISP, true},
    /* 0x98 */  {"RES 3, (IY%s), B", DISP, true},
    /* 0x99 */  {"RES 3, (IY%s), C", DISP, true},
    /* 0x9a */  {"RES 3, (IY%s), D", DISP, true},
    /* 0x9b */  {"RES 3, (IY%s), E", DISP, true},
    /* 0x9c */  {"RES 3, (IY%s), H", DISP, true},
    /* 0x9d */  {"RES 3, (IY%s), L", DISP, true},
    /* 0x9e */  {"RES 3, (IY%s)", DISP, false},
    /* 0x9f */  {"RES 3, (IY%s), A", DISP, true},
    /* 0xa0 */  {"RES 4, (IY%s), B", DISP, true},
    /* 0xa1 */  {"RES 4, (IY%s), C", DISP, true},
    /* 0xa2 */  {"RES 4, (IY%s), D", DISP, true},
    /* 0xa3 */  {"RES 4, (IY%s), E", DISP, true},
    /* 0xa4 */  {"RES 4, (IY%s), H", DISP, true},
    /* 0xa5 */  {"RES 4, (IY%s), L", DISP, true},
    /* 0xa6 */  {"RES 4, (IY%s)", DISP, false},
    /* 0xa7 */  {"RES 4, (IY%s), A", DISP, true},
    /* 0xa8 */  {"RES 5, (IY%s), B", DISP, true},
    /* 0xa9 */  {"RES 5, (IY%s), C", DISP, true},
    /* 0xaa */  {"RES 5, (IY%s), D", DISP, true},
    /* 0xab */  {"RES 5, (IY%s), E", DISP, true},
    /* 0xac */  {"RES 5, (IY%s), H", DISP, true},
    /* 0xad */  {"RES 5, (IY%s), L", DISP, true},
    /* 0xae */  {"RES 5, (IY%s)", DISP, false},
    /* 0xaf */  {"RES 5, (IY%s), A", DISP, true},
    /* 0xb0 */  {"RES 6, (IY%s), B", DISP, true},
    /* 0xb1 */  {"RES 6, (IY%s), C", DISP, true},
    /* 0xb2 */  {"RES 6, (IY%s), D", DISP, true},
    /* 0xb3 */  {"RES 6, (IY%s), E", DISP, true},
    /* 0xb4 */  {"RES 6, (IY%s), H", DISP, true},
    /* 0xb5 */  {"RES 6, (IY%s), L", DISP, true},
    /* 0xb6 */  {"RES 6, (IY%s)", DISP, false},
    /* 0xb7 */  {"RES 6, (IY%s), A", DISP, true},
    /* 0xb8 */  {"RES 7, (IY%s), B", DISP, true},
    /* 0xb9 */  {"RES 7, (IY%s), C", DISP, true},
    /* 0xba */  {"RES 7, (IY%s), D", DISP, true},
    /* 0xbb */  {"RES 7, (IY%s), E", DISP, true},
    /* 0xbc */  {"RES 7, (IY%s), H", DISP, true},
    /* 0xbd */  {"RES 7, (IY%s), L", DISP, true},
    /* 0xbe */  {"RES 7, (IY%s)", DISP, false},
    /* 0xbf */  {"RES 7, (IY%s), A", DISP, true},
    /* 0xc0 */  {"SET 0, (IY%s), B", DISP, true},
    /* 0xc1 */  {"SET 0, (IY%s), C", DISP, true},
    /* 0xc2 */  {"SET 0, (IY%s), D", DISP, true},
    /* 0xc3 */  {"SET 0, (IY%s), E", DISP, true},
    /* 0xc4 */  {"SET 0, (IY%s), H", DISP, true},
    /* 0xc5 */  {"SET 0, (IY%s), L", DISP, true},
    /* 0xc6 */  {"SET 0, (IY%s)", DISP, false},
    /* 0xc7 */  {"SET 0, (IY%s), A", DISP, true},
    /* 0xc8 */  {"SET 1, (IY%s), B", DISP, true},
    /* 0xc9 */  {"SET 1, (IY%s), C", DISP, true},
    /* 0xca */  {"SET 1, (IY%s), D", DISP, true},
    /* 0xcb */  {"SET 1, (IY%s), E", DISP, true},
    /* 0xcc */  {"SET 1, (IY%s), H", DISP, true},
    /* 0xcd */  {"SET 1, (IY%s), L", DISP, true},
    /* 0xce */  {"SET 1, (IY%s)", DISP, false},
    /* 0xcf */  {"SET 1, (IY%s), A", DISP, true},
    /* 0xd0 */  {"SET 2, (IY%s), B", DISP, true},
    /* 0xd1 */  {"SET 2, (IY%s), C", DISP, true},
    /* 0xd2 */  {"SET 2, (IY%s), D", DISP, true},
    /* 0xd3 */  {"SET 2, (IY%s), E", DISP, true},
    /* 0xd4 */  {"SET 2, (IY%s), H", DISP, true},
    /* 0xd5 */  {"SET 2, (IY%s), L", DISP, true},
    /* 0xd6 */  {"SET 2, (IY%s)", DISP, false},
    /* 0xd7 */  {"SET 2, (IY%s), A", DISP, true},
    /* 0xd8 */  {"SET 3, (IY%s), B", DISP, true},
    /* 0xd9 */  {"SET 3, (IY%s), C", DISP, true},
    /* 0xda */  {"SET 3, (IY%s), D", DISP, true},
    /* 0xdb */  {"SET 3, (IY%s), E", DISP, true},
    /* 0xdc */  {"SET 3, (IY%s), H", DISP, true},
    /* 0xdd */  {"SET 3, (IY%s), L", DISP, true},
    /* 0xde */  {"SET 3, (IY%s)", DISP, false},
    /* 0xdf */  {"SET 3, (IY%s), A", DISP, true},
    /* 0xe0 */  {"SET 4, (IY%s), B", DISP, true},
    /* 0xe1 */  {"SET 4, (IY%s), C", DISP, true},
    /* 0xe2 */  {"SET 4, (IY%s), D", DISP, true},
    /* 0xe3 */  {"SET 4, (IY%s), E", DISP, true},
    /* 0xe4 */  {"SET 4, (IY%s), H", DISP, true},
    /* 0xe5 */  {"SET 4, (IY%s), L", DISP, true},
    /* 0xe6 */  {"SET 4, (IY%s)", DISP, false},
    /* 0xe7 */  {"SET 4, (IY%s), A", DISP, true},
    /* 0xe8 */  {"SET 5, (IY%s), B", DISP, true},
    /* 0xe9 */  {"SET 5, (IY%s), C", DISP, true},
    /* 0xea */  {"SET 5, (IY%s), D", DISP, true},
    /* 0xeb */  {"SET 5, (IY%s), E", DISP, true},
    /* 0xec */  {"SET 5, (IY%s), H", DISP, true},
    /* 0xed */  {"SET 5, (IY%s), L", DISP, true},
    /* 0xee */  {"SET 5, (IY%s)", DISP, false},
    /* 0xef */  {"SET 5, (IY%s), A", DISP, true},
    /* 0xf0 */  {"SET 6, (IY%s), B", DISP, true},
    /* 0xf1 */  {"SET 6, (IY%s), C", DISP, true},
    /* 0xf2 */  {"SET 6, (IY%s), D", DISP, true},
    /* 0xf3 */  {"SET 6, (IY%s), E", DISP, true},
    /* 0xf4 */  {"SET 6, (IY%s), H", DISP, true},
    /* 0xf5 */  {"SET 6, (IY%s), L", DISP, true},
    /* 0xf6 */  {"SET 6, (IY%s)", DISP, false},
    /* 0xf7 */  {"SET 6, (IY%s), A", DISP, true},
    /* 0xf8 */  {"SET 7, (IY%s), B", DISP, true},
    /* 0xf9 */  {"SET 7, (IY%s), C", DISP, true},
    /* 0xfa */  {"SET 7, (IY%s), D", DISP, true},
    /* 0xfb */  {"SET 7, (IY%s), E", DISP, true},
    /* 0xfc */  {"SET 7, (IY%s), H", DISP, true},
    /* 0xfd */  {"SET 7, (IY%s), L", DISP, true},
    /* 0xfe */  {"SET 7, (IY%s)", DISP, false},
    /* 0xff */  {"SET 7, (IY%s), A", DISP, true},
};


std::uint8_t fetchUInt8(Disassembler::Line& res, std::uint16_t& pos, const std::vector<std::uint8_t>& memory) {
    std::uint8_t n = memory[pos++ % 0xffff];
    res.bytes.push_back(n);
    return n;
}

std::int8_t fetchInt8(Disassembler::Line& res, std::uint16_t& pos, const std::vector<std::uint8_t>& memory) {
    std::int8_t n = memory[pos++ % 0xffff];
    res.bytes.push_back(n);
    return n;
}

std::uint16_t fetchUInt16(Disassembler::Line& res, std::uint16_t& pos, const std::vector<std::uint8_t>& memory) {
    std::uint8_t n1 = memory[pos++ % 0xffff];
    std::uint8_t n2 = memory[pos++ % 0xffff];
    res.bytes.push_back(n1);
    res.bytes.push_back(n2);
    return n2<<8|n1;
}

InstrDesc fetchInstrDesc(std::uint16_t& pos, const std::vector<std::uint8_t>& memory, Disassembler::Line& line) {
    std::uint8_t b1, b2, b3, b4;

    b1 = fetchUInt8(line, pos, memory);

    InstrDesc instr;
    std::uint16_t param;
    bool fetchParam = true;
    switch(b1) {
    case 0xcb:
        b2 = fetchUInt8(line, pos, memory);
        instr = opcodes_cb[b2];
        break;
    case 0xdd:
        b2 = fetchUInt8(line, pos, memory);
        if (b2 == 0xcb) {
            param = fetchUInt8(line, pos, memory); // This is going to be the param.
            b4 = fetchUInt8(line, pos, memory);
            instr = opcodes_ddcb[b4];
        } else {
            instr = opcodes_dd[b2];
        }
        break;
    case 0xed:
        b2 = fetchUInt8(line, pos, memory);
        instr = opcodes_ed[b2];
        break;
    case 0xfd:
        b2 = fetchUInt8(line, pos, memory);
        if (b2 == 0xcb) {
            param = fetchUInt8(line, pos, memory); // This is going to be the param.
            b4 = fetchUInt8(line, pos, memory);
            instr = opcodes_fdcb[b4];
        } else {
            instr = opcodes_fd[b2];
        }
        break;
    default:
        instr = opcodes[b1];
    }
    return instr;
}

bool checkValidInstr(int depth, std::uint16_t pos, const std::vector<std::uint8_t>& memory, int len, bool illegalAllowed) {
    if (pos < 0 || pos+len > 0xffff) {
        // out of range
        return false;
    }
    Disassembler::Line res;
    InstrDesc instr = fetchInstrDesc(pos, memory, res);
    int actualLen = res.bytes.size();
    if (!(actualLen >= 2 && (res.bytes[0] == 0xdd || res.bytes[0] == 0xfd) && res.bytes[1] == 0xcb)) {
        switch(instr.param) {
        case ABS8:
        case REL:
        case DISP:
            actualLen++;
            break;
        case ABS16:
        case DISP_ABS8:
            actualLen+=2;
            break;
        }
    }

    if (len != actualLen) {
        // length is not matching
        return false;
    }
    if (!illegalAllowed && instr.illegal) {
        // illegal instructions not allowed
        return false;
    }
    return true;
}

}

std::vector<Disassembler::Line> DisassemblerZ80::disassembleBackward(std::uint16_t pos, const std::vector<std::uint8_t>& memory, int lines, const std::vector<Disassembler::Line>& disassemblyHint) {
    std::vector<Line> res;

    while(lines-- > 0 && (0 < pos && pos < memory.size())) {
        std::uint16_t p = pos;
        std::uint16_t tmp;
        if (checkValidInstr(0, pos - 3, memory, 3, /* illegalAllowed= */true)) {
            tmp = pos - 3;
            res.push_back(disassembleLine(tmp, memory));
            pos = p - 3;
        } else if (checkValidInstr(0, pos - 2, memory, 2, /* illegalAllowed= */true)) {
            tmp = pos - 2;
            res.push_back(disassembleLine(tmp, memory));
            pos = p - 2;
        } else if (checkValidInstr(0, pos - 1, memory, 1, /* illegalAllowed= */true)) {
            tmp = pos - 1;
            res.push_back(disassembleLine(tmp, memory));
            pos = p - 1;
        } else {
            // No valid instruction?
            pos--;
            Line l;
            l.addr = pos;
            std::uint8_t b = memory[pos % 0xffff];
            l.bytes.push_back(b);
            l.disassembly = "???";
            res.push_back(l);
        }
    }
    std::reverse(res.begin(), res.end());
    return res;
}

QString DisassemblerZ80::labelOrAddr(std::uint16_t addr, int len) const {
    QString label = symtab_->labelForAddress(addr).c_str();
    if (label.isEmpty()) {
        std::string format = "$%0" + std::to_string(len) + "X";
        label = QString::asprintf(format.c_str(), addr);
    }
    return label;
}

Disassembler::Line DisassemblerZ80::disassembleLine(std::uint16_t& pos, const std::vector<std::uint8_t>& memory) {

    Line res;
    res.addr = pos;

    InstrDesc instr = fetchInstrDesc(pos, memory, res);

    std::uint16_t param;
    bool fetchParam = true;
    if (res.bytes.size() >= 2 && (res.bytes[0] == 0xdd || res.bytes[0] == 0xfd) && res.bytes[1] == 0xcb) {
        fetchParam = false;
        param = res.bytes[2];
    }

    std::int16_t adj = 0;
    if (res.bytes[0] == 0xdd || res.bytes[0] == 0xed || res.bytes[0] == 0xfd) {
        adj = -1;
    }
    QString paramStr, paramStr2;
    switch(instr.param) {
    case NONE:
        break;
    case ABS8:
        if (fetchParam) {
            param = fetchUInt8(res, pos, memory);
        }
        paramStr = labelOrAddr(param,2);
        break;
    case ABS16:
        if (fetchParam) {
            param = fetchUInt16(res, pos, memory);
        }
        paramStr = labelOrAddr(param,4);
        break;
    case REL:
        if (fetchParam) {
            param = fetchInt8(res, pos, memory);
        }
        paramStr = QString::asprintf("$%04X", pos + adj + (std::int16_t)param);
        break;
    case DISP:
    {
        if (fetchParam) {
            param = fetchInt8(res, pos, memory);
        }
        bool neg = ((std::int16_t)param) < 0;
        if (neg) {
            param = - ((std::int16_t)param);
        }
        paramStr = QString::asprintf("%s$%02X", neg ? "-" : "+", param & 0xff);
    }
        break;
    case DISP_ABS8:
    {
        if (fetchParam) {
            param = fetchUInt16(res, pos, memory);
        }
        std::int16_t abs = param >> 8;
        std::int16_t disp = param & 0xff;
        bool neg = disp < 0;
        if (neg) {
            disp = -disp;
        }
        paramStr = QString::asprintf("%s$%02X", neg ? "-" : "+", disp);
        paramStr2 = QString::asprintf("$%02X", abs);
    }
        break;
    }
    res.disassembly = QString::asprintf(instr.instr.c_str(), paramStr.toStdString().c_str(),paramStr2.toStdString().c_str()).toStdString();
    if (instr.illegal && res.disassembly != "???") {
        res.disassembly = "*" + res.disassembly;
    }
    
    return res;
}


} // vicedebug
